---
title: "R Notebook"
output: html_notebook
---
```{r}
library(Seurat)
library(SeuratData)
library(SeuratWrappers)
library(dplyr)
library(ggpubr)
library(viridis)
library(scHolography)
```


```{r}
sp <- readRDS("/projects/b1042/YiLab/Cady/Code_3rdDraft/Mouse_Hippo_sim/visium.rds")
sc <- readRDS("/projects/b1042/YiLab/Cady/Code_3rdDraft/Mouse_Hippo_sim_match/SC/ref.sub.rds")

inter.gene <- intersect(rownames(sp@assays$Spatial@counts),rownames(sc@assays$RNA@counts))

integration.mat <- cbind(sp@assays$Spatial@counts[inter.gene,],sc@assays$RNA@counts[inter.gene,])

integration.obj <- CreateSeuratObject(integration.mat)

integration.obj[["Method"]] <- c(rep("sp",ncol(sp)),rep("sc",ncol(sc)))


############fastMNN

integration.obj <- NormalizeData(integration.obj)
integration.obj <- FindVariableFeatures(integration.obj)
integration.obj <- RunFastMNN(object.list = SplitObject(integration.obj, split.by = "Method"))
integration.obj <- RunUMAP(integration.obj, reduction = "mnn", dims = 1:30)
integration.obj <- FindNeighbors(integration.obj, reduction = "mnn", dims = 1:30)
integration.obj <- FindClusters(integration.obj)
DimPlot(integration.obj, group.by = c("Method", "ident"), ncol = 2)



#############Harmony
library(harmony)

integration.obj <- NormalizeData(integration.obj) %>% FindVariableFeatures() %>% ScaleData() %>% RunPCA(verbose = FALSE)
integration.obj <- RunHarmony(integration.obj, group.by.vars = "Method")
integration.obj <- RunUMAP(integration.obj, reduction = "harmony", dims = 1:30)
integration.obj <- FindNeighbors(integration.obj, reduction = "harmony", dims = 1:30) %>% FindClusters()
DimPlot(integration.obj, group.by = c("Method", "ident"), ncol = 2)



#############Liger
library(rliger)

# Please update your `liger` version to 0.5.0 or above before following this tutorial
integration.obj <- NormalizeData(integration.obj)
integration.obj <- FindVariableFeatures(integration.obj)
integration.obj <- ScaleData(integration.obj, split.by = "Method", do.center = FALSE)
integration.obj <- RunOptimizeALS(integration.obj, k = 50, lambda = 5, split.by = "Method")
integration.obj <- RunQuantileNorm(integration.obj, split.by = "Method")
# You can optionally perform Louvain clustering (`FindNeighbors` and `FindClusters`) after
# `RunQuantileNorm` according to your needs
integration.obj <- FindNeighbors(integration.obj, reduction = "iNMF", dims = 1:20)
integration.obj <- FindClusters(integration.obj, resolution = 0.3)
# Dimensional reduction and plotting
integration.obj <- RunUMAP(integration.obj, dims = 1:ncol(integration.obj[["iNMF"]]), reduction = "iNMF")
DimPlot(integration.obj, group.by = c("Method", "ident"), ncol = 2)


save.image("/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods/Example_SC.RData")
```




```{r}
load("/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods/Example_SC.RData")



options(future.globals.maxSize = 3000 * 1024^2)
sp.integrated <- dataAlign(low.res.sp =  sp,high.res.sp =  sc,nPCtoUse = 32,stProcessed = T,future.size = 7000)

###Harmony
sp.integrated@reductions$pca@cell.embeddings <- integration.obj@reductions$harmony@cell.embeddings[colnames(sp.integrated),1:ncol(sp.integrated@reductions$pca@cell.embeddings)]
brain.obj<-trainHolography(sp.integrated,n.repeat = 30)
saveRDS(brain.obj,"/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods/brain.obj.harmony_SC.rds" )

###Liger
sp.integrated@reductions$pca@cell.embeddings <- integration.obj@reductions$iNMF@cell.embeddings[colnames(sp.integrated),1:ncol(sp.integrated@reductions$pca@cell.embeddings)]
brain.obj<-trainHolography(sp.integrated,n.repeat = 30)
saveRDS(brain.obj,"/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods/brain.obj.liger_SC.rds" )

###fastMNN
sp.integrated@reductions$pca@cell.embeddings <- integration.obj@reductions$mnn@cell.embeddings[colnames(sp.integrated),1:ncol(sp.integrated@reductions$pca@cell.embeddings)]
brain.obj<-trainHolography(sp.integrated,n.repeat = 30)
saveRDS(brain.obj,"/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods/brain.obj.mnn_SC.rds" )

```




```{r}
hippo.vizgen.visium <- readRDS("/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods/scHolography.obj.rds")
ref.sub <- readRDS("/projects/b1042/YiLab/Cady/Code_3rdDraft/Mouse_Hippo_sim_match/SC/ref.sub.rds")
hippo.vizgen.visium_harmony <- readRDS("/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods/brain.obj.harmony_SC.rds" )
hippo.vizgen.visium_liger <- readRDS("/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods/brain.obj.liger_SC.rds" )
hippo.vizgen.visium_mnn <- readRDS("/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods/brain.obj.mnn_SC.rds")
```

```{r}
scene = list(camera = list(eye = list(x = 0, z = 1, y = 1.8)))
fig1 <- scHolographyPlot(hippo.vizgen.visium,color.by = "celltype",cells = which(hippo.vizgen.visium$scHolography.sc$celltype%in%c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells")),color = c(c("black",c("#d11141","#ffc425","#00aebd")),rep("black",15)))%>% plotly::layout(scene = scene)
fig1

```

```{r}
fig2 <- scHolographyPlot(hippo.vizgen.visium_harmony,color.by = "celltype",cells = which(hippo.vizgen.visium_harmony$scHolography.sc$celltype%in%c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells")),color = c(c("black",c("#d11141","#ffc425","#00aebd")),rep("black",15)))%>% plotly::layout(scene = scene)
fig2

```


```{r}
fig3 <- scHolographyPlot(hippo.vizgen.visium_liger,color.by = "celltype",cells = which(hippo.vizgen.visium_liger$scHolography.sc$celltype%in%c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells")),color = c(c("black",c("#d11141","#ffc425","#00aebd")),rep("black",15)))%>% plotly::layout(scene = scene)
fig3

```

```{r}
fig4 <- scHolographyPlot(hippo.vizgen.visium_mnn,color.by = "celltype",cells = which(hippo.vizgen.visium_mnn$scHolography.sc$celltype%in%c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells")),color = c(c("black",c("#d11141","#ffc425","#00aebd")),rep("black",15)))%>% plotly::layout(scene = scene)
fig4
```



```{r}
scHolo_CCA <- as.matrix(dist(hippo.vizgen.visium$scHolography.sc@meta.data[,c("z3d_sp","y3d_sp","x3d_sp")]))
scHolo_harmony  <- as.matrix(dist(hippo.vizgen.visium_harmony$scHolography.sc@meta.data[,c("z3d_sp","y3d_sp","x3d_sp")]))
scHolo_liger <- as.matrix(dist(hippo.vizgen.visium_liger$scHolography.sc@meta.data[,c("z3d_sp","y3d_sp","x3d_sp")]))
scHolo_mnn  <- as.matrix(dist(hippo.vizgen.visium_mnn$scHolography.sc@meta.data[,c("z3d_sp","y3d_sp","x3d_sp")]))

```


```{r}

findClusterDistance <- function(dist.mat, query.cluster,reference.cluster){
  out <- lapply(query.cluster, function(x){
    type <- colnames(ref.sub)[which(ref.sub$celltype %in% x)]
    base <- colnames(ref.sub)[which(ref.sub$celltype %in% reference.cluster)]
    dist.mat[intersect(type,colnames(dist.mat)),intersect(base,colnames(dist.mat))]
  })
  names(out) <- query.cluster
  out
}


scHolo_CCA.dist <- findClusterDistance(scHolo_CCA,query.cluster = c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells"),reference.cluster=c("CA3 Principal cells"))

scHolo_harmony.dist <- findClusterDistance(scHolo_harmony,query.cluster = c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells"),reference.cluster=c("CA3 Principal cells"))

scHolo_liger.dist <- findClusterDistance(scHolo_liger,query.cluster = c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells"),reference.cluster=c("CA3 Principal cells"))

scHolo_mnn.dist <- findClusterDistance(scHolo_mnn,query.cluster = c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells"),reference.cluster=c("CA3 Principal cells"))

```


```{r}


scHolo_CCA.dat <- data.frame(dist = unlist(lapply(scHolo_CCA.dist, rowMeans)),celltype = ref.sub$celltype[unlist(lapply(names(unlist(lapply(scHolo_CCA.dist, rowMeans))),function(x) unlist(strsplit(x,split = "[.]"))[-1]))])

scHolo_harmony.dat <- data.frame(dist = unlist(lapply(scHolo_harmony.dist, rowMeans)),celltype = ref.sub$celltype[unlist(lapply(names(unlist(lapply(scHolo_harmony.dist, rowMeans))),function(x) unlist(strsplit(x,split = "[.]"))[-1]))])

scHolo_liger.dat <- data.frame(dist = unlist(lapply(scHolo_liger.dist, rowMeans)),celltype = ref.sub$celltype[unlist(lapply(names(unlist(lapply(scHolo_liger.dist, rowMeans))),function(x) unlist(strsplit(x,split = "[.]"))[-1]))])

scHolo_mnn.dat <- data.frame(dist = unlist(lapply(scHolo_mnn.dist, rowMeans)),celltype = ref.sub$celltype[unlist(lapply(names(unlist(lapply(scHolo_mnn.dist, rowMeans))),function(x) unlist(strsplit(x,split = "[.]"))[-1]))])

```

```{r}
scHolo_CCA.dat$celltype <- factor(as.character(scHolo_CCA.dat$celltype),levels = stringr::str_sort(unique(as.character(scHolo_CCA.dat$celltype)),numeric = T))
scHolo_harmony.dat$celltype <- factor(as.character(scHolo_harmony.dat$celltype),levels = stringr::str_sort(unique(as.character(scHolo_harmony.dat$celltype)),numeric = T))
scHolo_liger.dat$celltype <- factor(as.character(scHolo_liger.dat$celltype),levels = stringr::str_sort(unique(as.character(scHolo_liger.dat$celltype)),numeric = T))
scHolo_mnn.dat$celltype <- factor(as.character(scHolo_mnn.dat$celltype),levels = stringr::str_sort(unique(as.character(scHolo_mnn.dat$celltype)),numeric = T))
```


```{r}
library(ggpubr)
library(scHolography)
my_comparisons <- list( c("CA1 Principal cells","CA2 Principal cells"), c("CA2 Principal cells","CA3 Principal cells"))

ggplot(scHolo_CCA.dat, aes(x=celltype, y=dist/mean(scHolo_CCA.dat[which(scHolo_CCA.dat$celltype=="CA3 Principal cells"),"dist"]), fill=celltype)) +
  geom_boxplot()+theme_classic()+scale_fill_manual(values = c("#d11141","#ffc425","#00aebd"))+ 
  geom_signif(comparisons = my_comparisons,test.args = list(size=5),map_signif_level = TRUE)+ theme(axis.title.x = element_blank(),axis.title.y = element_blank(),axis.text = element_text(size = 15,face = "bold"))+NoLegend()+
  scale_x_discrete(labels=c("CA1","CA2","CA3"))


tiff("/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods//CAs.Dist.scHolo_harmony.tiff", units="in", width=4.5, height=6, res=300)
ggplot(scHolo_harmony.dat, aes(x=celltype, y=dist/mean(scHolo_harmony.dat[which(scHolo_harmony.dat$celltype=="CA3 Principal cells"),"dist"]), fill=celltype)) +
  geom_boxplot()+theme_classic()+scale_fill_manual(values = c("#d11141","#ffc425","#00aebd"))+ 
  geom_signif(comparisons = my_comparisons,test.args = list(size=5),map_signif_level = TRUE)+ theme(axis.title.x = element_blank(),axis.title.y = element_blank(),axis.text = element_text(size = 15,face = "bold"))+NoLegend()+
  scale_x_discrete(labels=c("CA1","CA2","CA3"))
dev.off()


tiff("/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods//CAs.Dist.scHolo_liger.tiff", units="in", width=4.5, height=6, res=300)
ggplot(scHolo_liger.dat, aes(x=celltype, y=dist/mean(scHolo_liger.dat[which(scHolo_liger.dat$celltype=="CA3 Principal cells"),"dist"]), fill=celltype)) +
  geom_boxplot()+theme_classic()+scale_fill_manual(values = c("#d11141","#ffc425","#00aebd"))+ 
  geom_signif(comparisons = my_comparisons,test.args = list(size=5),map_signif_level = TRUE)+ theme(axis.title.x = element_blank(),axis.title.y = element_blank(),axis.text = element_text(size = 15,face = "bold"))+NoLegend()+
  scale_x_discrete(labels=c("CA1","CA2","CA3"))
dev.off()


tiff("/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods//CAs.Dist.scHolo_mnn.tiff", units="in", width=4.5, height=6, res=300)
ggplot(scHolo_mnn.dat, aes(x=celltype, y=dist/mean(scHolo_mnn.dat[which(scHolo_mnn.dat$celltype=="CA3 Principal cells"),"dist"]), fill=celltype)) +
  geom_boxplot()+theme_classic()+scale_fill_manual(values = c("#d11141","#ffc425","#00aebd"))+ 
  geom_signif(comparisons = my_comparisons,test.args = list(size=5),map_signif_level = TRUE)+ theme(axis.title.x = element_blank(),axis.title.y = element_blank(),axis.text = element_text(size = 15,face = "bold"))+NoLegend()+
  scale_x_discrete(labels=c("CA1","CA2","CA3"))
dev.off()

```


```{r}
save.image("/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods/eval_brain_SC.RData")
```






