---
title: "R Notebook"
output: html_notebook
---
```{r}
library(Seurat)
library(dplyr)
library(ggpubr)
library(viridis)
library(SeuratData)
library(SeuratWrappers)
library(ggplot2)
```


```{r}

sp <- readRDS("/projects/b1042/YiLab/Cady/Code_3rdDraft/Mouse_Hippo_sim/visium.rds")
sc <- readRDS("/projects/b1042/YiLab/Cady/Code_3rdDraft/Mouse_Hippo_sim/vizgen.hippo.rds")

inter.gene <- intersect(rownames(sp@assays$Spatial@counts),rownames(sc@assays$RNA@counts))

integration.mat <- cbind(sp@assays$Spatial@counts[inter.gene,],sc@assays$RNA@counts[inter.gene,])

integration.obj <- CreateSeuratObject(integration.mat)

integration.obj[["Method"]] <- c(rep("sp",ncol(sp)),rep("sc",ncol(sc)))


############fastMNN

integration.obj <- NormalizeData(integration.obj)
integration.obj <- FindVariableFeatures(integration.obj)
integration.obj <- RunFastMNN(object.list = SplitObject(integration.obj, split.by = "Method"))
integration.obj <- RunUMAP(integration.obj, reduction = "mnn", dims = 1:30)
integration.obj <- FindNeighbors(integration.obj, reduction = "mnn", dims = 1:30)
integration.obj <- FindClusters(integration.obj)
DimPlot(integration.obj, group.by = c("Method", "ident"), ncol = 2)

fastMNNplot <- DimPlot(integration.obj, group.by = c("Method"))
tiff("/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods/fastMNN.integration.tiff", units="in", width=6, height=6, res=600)
fastMNNplot+ggtitle("fastMNN")
dev.off()


#############Harmony
library(harmony)

integration.obj <- NormalizeData(integration.obj) %>% FindVariableFeatures() %>% ScaleData() %>% RunPCA(verbose = FALSE)
integration.obj <- RunHarmony(integration.obj, group.by.vars = "Method")
integration.obj <- RunUMAP(integration.obj, reduction = "harmony", dims = 1:30)
integration.obj <- FindNeighbors(integration.obj, reduction = "harmony", dims = 1:30) %>% FindClusters()
DimPlot(integration.obj, group.by = c("Method", "ident"), ncol = 2)

HarmonyPlot <- DimPlot(integration.obj, group.by = c("Method"))
tiff("/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods/harmony.integration.tiff", units="in", width=6, height=6, res=600)
HarmonyPlot+ggtitle("Harmony")
dev.off()

#############Liger
library(rliger)

# Please update your `liger` version to 0.5.0 or above before following this tutorial
integration.obj <- NormalizeData(integration.obj)
integration.obj <- FindVariableFeatures(integration.obj)
integration.obj <- ScaleData(integration.obj, split.by = "Method", do.center = FALSE)
integration.obj <- RunOptimizeALS(integration.obj, k = 50, lambda = 5, split.by = "Method")
integration.obj <- RunQuantileNorm(integration.obj, split.by = "Method")
# You can optionally perform Louvain clustering (`FindNeighbors` and `FindClusters`) after
# `RunQuantileNorm` according to your needs
integration.obj <- FindNeighbors(integration.obj, reduction = "iNMF", dims = 1:20)
integration.obj <- FindClusters(integration.obj, resolution = 0.3)
# Dimensional reduction and plotting
integration.obj <- RunUMAP(integration.obj, dims = 1:ncol(integration.obj[["iNMF"]]), reduction = "iNMF")
DimPlot(integration.obj, group.by = c("Method", "ident"), ncol = 2)

ligerPlot <- DimPlot(integration.obj, group.by = c("Method"))
tiff("/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods/liger.integration.tiff", units="in", width=6, height=6, res=600)
ligerPlot+ggtitle("LIGER")
dev.off()

```

```{r}
load("/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods/Example.RData")

options(future.globals.maxSize = 3000 * 1024^2)
sp.integrated <- dataAlign(low.res.sp =  sp,high.res.sp =  sc,nPCtoUse = 32,stProcessed = T,scProcessed = T,future.size = 7000)

###Harmony
sp.integrated@reductions$pca@cell.embeddings <- integration.obj@reductions$harmony@cell.embeddings[colnames(sp.integrated),1:ncol(sp.integrated@reductions$pca@cell.embeddings)]
brain.obj<-trainHolography(sp.integrated,n.repeat = 30,fov = "s2r1",which.fov = 2)
saveRDS(brain.obj,"/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods/brain.obj.harmony.rds" )

###Liger
sp.integrated@reductions$pca@cell.embeddings <- integration.obj@reductions$iNMF@cell.embeddings[colnames(sp.integrated),1:ncol(sp.integrated@reductions$pca@cell.embeddings)]
brain.obj<-trainHolography(sp.integrated,n.repeat = 30,fov = "s2r1",which.fov = 2)
saveRDS(brain.obj,"/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods/brain.obj.liger.rds" )

###fastMNN
sp.integrated@reductions$pca@cell.embeddings <- integration.obj@reductions$mnn@cell.embeddings[colnames(sp.integrated),1:ncol(sp.integrated@reductions$pca@cell.embeddings)]
brain.obj<-trainHolography(sp.integrated,n.repeat = 30,fov = "s2r1",which.fov = 2)
saveRDS(brain.obj,"/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods/brain.obj.mnn.rds" )

```


```{r}
vizgen.hippo <- readRDS("/projects/b1042/YiLab/Cady/Code_3rdDraft/Mouse_Hippo_sim/vizgen.hippo.rds")
hippo.vizgen.visium <- readRDS("/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods/hippo.vizgen.visium.rds")
hippo.vizgen.visium_harmony <- readRDS("/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods/brain.obj.harmony.rds" )
hippo.vizgen.visium_liger <- readRDS("/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods/brain.obj.liger.rds" )
hippo.vizgen.visium_mnn <- readRDS("/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods/brain.obj.mnn.rds")
```



```{r}
real <- as.matrix(dist(GetTissueCoordinates(vizgen.hippo)[,c("x","y")]))
colnames(real) <- colnames(vizgen.hippo)
rownames(real) <- colnames(vizgen.hippo)



scHolo_CCA <- igraph::distances(igraph::graph_from_adjacency_matrix(hippo.vizgen.visium$adj.mtx, mode = "undirected"), mode = "out")
colnames(scHolo_CCA) <- colnames(hippo.vizgen.visium$scHolography.sc)
rownames(scHolo_CCA)<- colnames(hippo.vizgen.visium$scHolography.sc)

scHolo_harmony <- igraph::distances(igraph::graph_from_adjacency_matrix(hippo.vizgen.visium_harmony$adj.mtx, mode = "undirected"), mode = "out")
colnames(scHolo_harmony) <- colnames(hippo.vizgen.visium_harmony$scHolography.sc)
rownames(scHolo_harmony)<- colnames(hippo.vizgen.visium_harmony$scHolography.sc)

scHolo_liger <- igraph::distances(igraph::graph_from_adjacency_matrix(hippo.vizgen.visium_liger$adj.mtx, mode = "undirected"), mode = "out")
colnames(scHolo_liger) <- colnames(hippo.vizgen.visium_liger$scHolography.sc)
rownames(scHolo_liger)<- colnames(hippo.vizgen.visium_liger$scHolography.sc)

scHolo_mnn <-igraph::distances(igraph::graph_from_adjacency_matrix(hippo.vizgen.visium_mnn$adj.mtx, mode = "undirected"), mode = "out")
colnames(scHolo_mnn) <- colnames(hippo.vizgen.visium_mnn$scHolography.sc)
rownames(scHolo_mnn)<- colnames(hippo.vizgen.visium_mnn$scHolography.sc)

```

```{r}
same.cell  <- Reduce(intersect, list(colnames(real), colnames(scHolo_CCA),colnames(scHolo_liger),colnames(scHolo_mnn),colnames(scHolo_harmony)))

scHolo_CCA_cor <- unlist(lapply(same.cell, function(i) cor(real[same.cell,i],scHolo_CCA[same.cell,i],method = "spearman")))
scHolo_harmony_cor <- unlist(lapply(same.cell, function(i) cor(real[same.cell,i],scHolo_harmony[same.cell,i],method = "spearman")))
scHolo_liger_cor <- unlist(lapply(same.cell, function(i) cor(real[same.cell,i],scHolo_liger[same.cell,i],method = "spearman")))
scHolo_mnn_cor <- unlist(lapply(same.cell, function(i) cor(real[same.cell,i],scHolo_mnn[same.cell,i],method = "spearman")))
```
```{r}
sp.cor.scholo.cca.harm.liger.mnn <- data.frame(Seurat_CCA=scHolo_CCA_cor, Harmony=scHolo_harmony_cor, LIGER=scHolo_liger_cor, fastMNN=scHolo_mnn_cor)
sp.cor.scholo.cca.harm.liger.mnn_melt <- reshape2::melt(sp.cor.scholo.cca.harm.liger.mnn)

my_comparisons <- list( c("Seurat_CCA","Harmony"), c("Seurat_CCA","LIGER"), c("Seurat_CCA","fastMNN"))
tiff("/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods//sp.cor.scholo.cca.harm.liger.mnn.plot.tiff", units="in", width=6, height=8, res=300)
ggplot(sp.cor.scholo.cca.harm.liger.mnn_melt, aes(x = variable, y = value, fill = variable)) +
  geom_boxplot() +
  theme_classic() +
  labs(title = "", 
       x = "", 
       y = "Correlation (spearman)")+ theme(axis.title.x = element_blank(),axis.title.y = element_text(size = 16,face = "bold"),axis.text = element_text(size = 15,face = "bold"))+NoLegend()+
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") + 
  geom_signif(comparisons = my_comparisons,test.args = list(size=5),map_signif_level = TRUE,y_position = c(.3,.35,.4))+scale_fill_brewer(palette = "Set3") 
dev.off()

```


```{r}
scHolo_CCA <- as.matrix(dist(hippo.vizgen.visium$scHolography.sc@meta.data[,c("z3d_sp","y3d_sp","x3d_sp")]))
scHolo_harmony <- as.matrix(dist(hippo.vizgen.visium_harmony$scHolography.sc@meta.data[,c("z3d_sp","y3d_sp","x3d_sp")]))
scHolo_liger <- as.matrix(dist(hippo.vizgen.visium_liger$scHolography.sc@meta.data[,c("z3d_sp","y3d_sp","x3d_sp")]))
scHolo_mnn <- as.matrix(dist(hippo.vizgen.visium_mnn$scHolography.sc@meta.data[,c("z3d_sp","y3d_sp","x3d_sp")]))

findKL<-function(realmat,mat){
  realmat.sub <- realmat[rownames(mat),colnames(mat)]
  
  out <- lapply(rownames(mat),function(nam){
    eps <- 1e-20
    X_ <- cbind(realmat.sub[nam,],mat[nam,])
    X_[X_ < eps] <- eps
    X_ <- scale(X_, center = F, scale = colSums(X_)) %>% data.frame
    KL_D <- suppressMessages(philentropy::KL(t(X_), unit = "log"))
    KL_D
  })
  out <- unlist(out)
  names(out) <- rownames(mat)
  out
}


scHolo_CCA.kl<-findKL(realmat =real ,mat = scHolo_CCA)
scHolo_harmony.kl<-findKL(realmat =real ,mat = scHolo_harmony)
scHolo_liger.kl<-findKL(realmat = real,mat = scHolo_liger)
scHolo_mnn.kl<-findKL(realmat = real,mat = scHolo_mnn)
```


```{r}
kl <- c(scHolo_CCA.kl,scHolo_harmony.kl,scHolo_liger.kl,scHolo_mnn.kl)
method<-c(rep("scHolo_cca",length(scHolo_CCA.kl)),rep("scHolo_harmony",length(scHolo_harmony.kl)),rep("scHolo_liger",length(scHolo_liger.kl)),
          rep("scHolo_mnn",length(scHolo_mnn.kl)))

df <- data.frame(kl=kl, method=factor(method,levels = (c("scHolo_cca","scHolo_harmony","scHolo_liger","scHolo_mnn"))))


my_comparisons <- list( c("scHolo_cca","scHolo_harmony"),c("scHolo_cca","scHolo_liger"),c("scHolo_cca","scHolo_mnn"))

tiff("/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods//KL_Divergence.tiff", units="in", width=6, height=8, res=600)
ggplot(df, aes(x=method, y=kl, fill=method)) +
  geom_boxplot()+theme_classic()+
  geom_signif(comparisons = my_comparisons,test.args = list(size=7),map_signif_level = TRUE,y_position = c(.8/2,.86667/2,.93333/2))+ theme(axis.title.x = element_blank(),axis.title.y = element_text(size = 16,face = "bold"),axis.text = element_text(size = 15,face = "bold"))+NoLegend()+ylim(c(0,.55))+scale_fill_brewer(palette = "Set3")+ylab("K-L Divergence")
dev.off()
```


```{r}
neighbor.eval2 <- function(dist.mat,max.neighbor,n.by,start){
  bench <-real
  expr <- vizgen.hippo@assays$Vizgen@counts
  test <- dist.mat
  diag(bench)<-10^15
  diag(test)<-10^15
  
  neighbor.comp.corr.mtx <- c()
  for (i in seq(start+1,(max.neighbor+1),by=n.by)) {
    
    nn.real.ls <- lapply(colnames(dist.mat), function(x) {
      ind <- which(bench[x,colnames(dist.mat)]<=sort(bench[x,colnames(dist.mat)])[i])
      #show(expr[,colnames(dist.mat[,ind])])
      rowSums(as.matrix(expr[,colnames(dist.mat[,ind])]))
    })
    
    nn.ls <- lapply(colnames(dist.mat), function(x) {
      ind <- which(test[x,colnames(dist.mat)]<=sort(test[x,colnames(dist.mat)])[i])
      rowSums(as.matrix(expr[,colnames(dist.mat[,ind])]))
    })
    
    neighbor.comp.corr <- unlist(lapply(1:length(nn.ls), function(x) {
      lsa::cosine(nn.real.ls[[x]],nn.ls[[x]])
    }))
    neighbor.comp.corr.mtx <- c(neighbor.comp.corr.mtx,neighbor.comp.corr)
    
  }
  
  neighbor.comp.corr.mtx <- matrix(neighbor.comp.corr.mtx,ncol = max.neighbor/n.by)
  (neighbor.comp.corr.mtx)
}
```



```{r}
a.3 <- neighbor.eval2(scHolo_CCA,50,1,1)
b.3 <- neighbor.eval2(scHolo_harmony,50,1,1)
c.3 <- neighbor.eval2(scHolo_liger,50,1,1)
d.3 <- neighbor.eval2(scHolo_mnn,50,1,1)


```

```{r}
cor.mean <- c(colMeans(a.3[,c(seq(3,15,by=3)-1)]),colMeans(b.3[,c(seq(3,15,by=3)-1)]),colMeans(c.3[,c(seq(3,15,by=3)-1)]),colMeans(d.3[,c(seq(3,15,by=3)-1)]))
num.neighbor <- rep(seq(3,15,by=3),4)
method<-c(rep("scHolo_cca",5),rep("scHolo_harmony",5),rep("scHolo_liger",5),rep("scHolo_mnn",5))
df <- data.frame(mean=cor.mean, method=factor(method,levels = rev(c("scHolo_cca","scHolo_harmony","scHolo_liger","scHolo_mnn"))),
                 num.neighbor=factor(num.neighbor,levels = stringr::str_sort(unique(num.neighbor),numeric = T)))

tiff("/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods/benchmark.cosine.heat.tiff", units="in", width=10, height=6, res=600)
ggplot(df, aes(num.neighbor, method, fill= mean)) +
  geom_tile() +
  scale_fill_viridis(discrete=FALSE)+theme_classic()+theme(axis.text = element_text(size = 15,face = "bold"),axis.text.x = element_text(angle = 45,hjust=1),axis.title=element_text(size = 18,face = "bold"),legend.title =element_text(size = 13,face = "bold"),legend.text =element_text(size = 12,face = "bold"))+xlab("Size of Neighborhood")+ylab("Methods")+ labs(fill="Mean of Cosine Similarity")+geom_text(aes(label = round(mean, 3)),size=7)
dev.off()

```


```{r}
save.image("/projects/b1042/YiLab/Cady/Code_3rdDraft/Integration Methods/eval_brain.RData")
```





