---
title: "R Notebook"
output: html_notebook
---


```{r}
library(scHolography)
```

```{r}
low.res.sp<-Seurat::Load10X_Spatial("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Data/human/st_Foreskin/20220712/A1/")
high.res.sp<-readRDS("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Spatial Transcriptomics/VAE/f2.rds")
sp.integrated <- dataAlign(low.res.sp,high.res.sp,nPCtoUse = 32,scProcessed = T)
scHolography.obj<-trainHolography(sp.integrated,n.slot = 30,n.pcUse = 32,n.pcOut = 32,n.repeat = 30)
scHolographyPlot(scHolography.obj)
```

```{r}
high.res.sp$celltype<-as.character(high.res.sp$seurat_clusters)
high.res.sp$celltype[which(high.res.sp$celltype%in%c("2","6","8"))]<-"Suprabasal"
high.res.sp$celltype[which(high.res.sp$celltype%in%c("3","10","17"))]<-"Basal"
high.res.sp$celltype[which(high.res.sp$celltype%in%c("5"))]<-"Melanocyte"
high.res.sp$celltype[which(high.res.sp$celltype%in%c("0","1","16","7"))]<-"Dermal"
high.res.sp$celltype[which(high.res.sp$celltype%in%c("9","11"))]<-"Endothelial"
high.res.sp$celltype[which(high.res.sp$celltype%in%c("15","18"))]<-"Immune"
high.res.sp$celltype[which(high.res.sp$celltype%in%c("12"))]<-"Schwann"
high.res.sp$celltype[which(high.res.sp$celltype%in%c("14"))]<-"Smooth Muscle"
high.res.sp$celltype[which(high.res.sp$celltype%in%c("4"))]<-"Glandular Epithelium"
high.res.sp$celltype[which(high.res.sp$celltype%in%c("13"))]<-"Lymphatic Endothelial"
high.res.sp$celltype<-as.factor(high.res.sp$celltype)
Seurat::DimPlot(high.res.sp,group.by = "celltype",cols = c("#A6CEE3","#79C360", "#3F8EAA",  "#B89B74", "#E52829", "#FDB762", "#ED8F47", "#9471B4" ,"#DDD399" ,"#B15928"))


tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human Skin/scFS.tiff", units="in", width=10, height=8, res=300)
Seurat::DimPlot(high.res.sp,group.by = "celltype",cols = c("#A6CEE3","#79C360", "#3F8EAA",  "#B89B74", "#E52829", "#FDB762", "#ED8F47", "#9471B4" ,"#DDD399" ,"#B15928"))+NoLegend()+ggplot2::ggtitle("")
dev.off()
```


```{r}
library(dplyr)
scHolography.obj$scHolography.sc$celltype<- factor(as.character(scHolography.obj$scHolography.sc$celltype),levels = c("Basal" ,"Endothelial","Dermal",  "Glandular Epithelium","Immune" , "Lymphatic Endothelial" ,"Melanocyte" ,"Schwann" ,"Smooth Muscle"  , "Suprabasal"  ))
#scHolography.obj$scHolography.sc$z3d_sp <- -scHolography.obj$scHolography.sc$z3d_sp
#scHolography.obj$scHolography.sc$x3d_sp <- -scHolography.obj$scHolography.sc$x3d_sp
#scHolography.obj$scHolography.sc$y3d_sp <- -scHolography.obj$scHolography.sc$y3d_sp
scene = list(camera = list(eye = list(x = -1, z = 0, y = 2)))
fig1<-scHolographyPlot(scHolography.obj,color.by = "celltype")%>% plotly::layout(scene = scene)
fig2<-scHolographyPlot(scHolography.obj,feature  = "KRT10")%>% plotly::layout(scene = scene)
fig3<-scHolographyPlot(scHolography.obj,feature = "KRT5")%>% plotly::layout(scene = scene)
fig4<-scHolographyPlot(scHolography.obj,feature = "COL1A2")%>% plotly::layout(scene = scene)
fig5<-scHolographyPlot(scHolography.obj,feature = "ACTA2")%>% plotly::layout(scene = scene)


plotly::orca(fig1, "3dct.svg",width = 7,height = 5)
plotly::orca(fig2, "3dct.KRT10.svg",width = 7,height = 5)
plotly::orca(fig3, "3dct.KRT5.svg",width = 7,height = 5)
plotly::orca(fig4, "3dct.COL1A2.svg",width = 7,height = 5)
plotly::orca(fig5, "3dct.ACTA2.svg",width = 7,height = 5)

```


```{r}
scene = list(camera = list(eye = list(x = -1, z = 0, y = 2)))

fig.L1 <- (scHolographyPlot(scHolography.obj,color.by = "celltype",cells = which(scHolography.obj$scHolography.sc$celltype%in%c("Suprabasal")))%>% plotly::layout(scene = scene) )
plotly::orca(fig.L1, "3dct.sub.L1.svg",width = 7,height = 5)

fig.L2 <- (scHolographyPlot(scHolography.obj,color.by = "celltype",cells = which(scHolography.obj$scHolography.sc$celltype%in%c("Suprabasal","Basal")))%>% plotly::layout(scene = scene) )
plotly::orca(fig.L2, "3dct.sub.L2.svg",width = 7,height = 5)

fig.L3 <- (scHolographyPlot(scHolography.obj,color.by = "celltype",cells = which(scHolography.obj$scHolography.sc$celltype%in%c("Suprabasal","Basal","Dermal")))%>% plotly::layout(scene = scene) )
plotly::orca(fig.L3, "3dct.sub.L3.svg",width = 7,height = 5)

fig.L4 <- (scHolographyPlot(scHolography.obj,color.by = "celltype",cells = which(scHolography.obj$scHolography.sc$celltype%in%c("Suprabasal","Basal","Dermal", "Smooth Muscle")))%>% plotly::layout(scene = scene) )
plotly::orca(fig.L4, "3dct.sub.L4.svg",width = 7,height = 5)
```





```{r}
library(ggpubr)
my_comparisons <- list( c("Suprabasal", "Basal"), c("Basal", "Dermal"), c("Dermal", "Smooth Muscle") )
tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human Skin//clusterDist.celltype.comp.tiff", units="in", width=7, height=5, res=300)
scHolography::clusterDistanceBoxplot(scHolography.obj,annotationToUse = "celltype",reference.cluster = "Smooth Muscle",query.cluster.list = c("Suprabasal","Basal","Dermal","Smooth Muscle"))+ 
  stat_compare_means(comparisons = my_comparisons)
dev.off()
```
```{r}
library(plotly)
index <- c(which(scHolography.obj$adj.mtx[88,]>0)) 
index.new <- c(rep(88, length(index)),index)
df <- data.frame(index=index.new ,x=scHolography.obj$scHolography.sc$x3d_sp[index.new],y=scHolography.obj$scHolography.sc$y3d_sp[index.new],z=scHolography.obj$scHolography.sc$z3d_sp[index.new],x2d=scHolography.obj$scHolography.sc$x_sp[index.new],y2d=scHolography.obj$scHolography.sc$y_sp[index.new],celltype=scHolography.obj$scHolography.sc$celltype[index.new],group=rep(1:length(index),2))
#ggplot(df, aes(x, -y, group = group,color=celltype)) + geom_line(color="grey")+geom_point() + theme_classic()
fig <- plot_ly() %>%
  add_trace(x = df$x, y = df$y, z = df$z, color = df$celltype, 
            type = "scatter3d", mode = "markers",marker=list(size=25),colors=c(colorRampPalette(RColorBrewer::brewer.pal(12,"Paired"))(10))) %>%
  add_trace(x = df$x, y = df$y, z = df$z, split = df$group, 
            line = list(width = 12, color = "red"),
            type = "scatter3d" ,mode = "lines", showlegend = FALSE, inherit = FALSE)%>% plotly::layout(scene = scene) %>%plotly::layout(scene=list(xaxis = list(showticklabels = F,gridwidth=15), yaxis = list( showticklabels = F,gridwidth=15),  zaxis = list(showticklabels = F,gridwidth=15)))
fig
plotly::orca(fig, "Basal88FirstDegreeNeighbor.svg",width = 7*300,height = 5*300)
```

```{r}
my.color.order= c("#A6CEE3" ,"#79C360", "#3F8EAA" ,colorRampPalette(RColorBrewer::brewer.pal(12,"Paired"))(10)[4:10] )
plots <- scHolographyNeighborCompPlot(scHolography.obj,annotationToUse = "celltype",query.cluster = c("Suprabasal","Basal","Glandular Epithelium","Dermal","Endothelial","Lymphatic Endothelial","Smooth Muscle", "Schwann","Immune","Melanocyte"))

tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human Skin//microenvironment.tiff", units="in", width=10, height=5, res=600)
plots$neighbor.comp.plot+scale_fill_manual(values = my.color.order)
dev.off()
```