---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Seurat)
library(scHolography)
scHolography.obj <-readRDS("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human Skin/scHolography.obj_new.rds")

```

```{r}

spatial.neighbor.Dermal <- findSpatialNeighborhood(scHolography.obj ,annotationToUse = "celltype",query.cluster = c("Dermal"),orig.assay = "RNA")
```

```{r}
library(dplyr)
library(Seurat)

spatial.neighbor.Dermal$scHolography.obj$scHolography.sc$spatial.neighborhood[which(spatial.neighbor.Dermal$scHolography.obj$scHolography.sc$spatial.neighborhood%in%c(as.character(1:4)))] <- paste0("Dermal_",spatial.neighbor.Dermal$scHolography.obj$scHolography.sc$spatial.neighborhood[which(spatial.neighbor.Dermal$scHolography.obj$scHolography.sc$spatial.neighborhood%in%c(as.character(1:4)))])

fib.sp.col <-  c(c(colorRampPalette(RColorBrewer::brewer.pal(12,"Paired"))(10)[1],(RColorBrewer::brewer.pal(4,"Greens"))),colorRampPalette(RColorBrewer::brewer.pal(12,"Paired"))(10)[c(2,4:10)])
neighbor.comp <- scHolography::scHolographyNeighborCompPlot(spatial.neighbor.Dermal$scHolography.obj,annotationToUse = "spatial.neighborhood",query.cluster = paste0("Dermal_",1:4),color = fib.sp.col)
library(ggplot2)
tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human Skin/Fib.spatial.neighbor.comp.tiff", units="in", width=5, height=6, res=600)
neighbor.comp$neighbor.comp.plot+theme(axis.text = element_text(size = 16,face = "bold"),axis.title.x = element_blank(),axis.title.y = element_text(size = 20,face = "bold") ,axis.text.x = element_text(angle = 30,hjust=1))+NoLegend()
dev.off()

```

```{r}
spatial.neighbor.Dermal$neighbor.marker %>%
  group_by(cluster) %>%
  top_n(n = 10, wt = avg_log2FC) -> top10
DoHeatmap(spatial.neighbor.Dermal$bulk.count.obj,assay = "SCT", features = top10$gene) + NoLegend()+viridis::scale_fill_viridis()
spatial.neighbor.Dermal$sc.marker %>%
  group_by(cluster) %>%
  top_n(n = 10, wt = avg_log2FC) -> top10b
DoHeatmap(spatial.neighbor.Dermal$query.only.obj$scHolography.sc,assay = "SCT", features = top10b$gene,group.by = "spatial.neighborhood") + NoLegend()+viridis::scale_fill_viridis()
library(RColorBrewer)

fib.sp.col <-  c(c(colorRampPalette(brewer.pal(12,"Paired"))(10)[1],(brewer.pal(4,"Greens"))),colorRampPalette(brewer.pal(12,"Paired"))(10)[c(2,4:10)])


scene = list(camera = list(eye = list(x = -1, z = 0, y = 2)))

fig1 <- scHolography::scHolographyPlot(spatial.neighbor.Dermal$scHolography.obj,color.by = "spatial.neighborhood",color = fib.sp.col)%>% plotly::layout(scene = scene)
plotly::orca(fig1, "3d.fib.all.celltype.svg",width = 7,height = 5)

fig2 <- scHolography::scHolographyPlot(spatial.neighbor.Dermal$scHolography.obj,color.by = "spatial.neighborhood",color = fib.sp.col, cells = which(spatial.neighbor.Dermal$scHolography.obj$scHolography.sc$celltype%in%c("Basal","Dermal","Smooth Muscle")))%>% plotly::layout(scene = scene)
plotly::orca(fig2, "3d.fib.basal.derm.sm.svg",width = 7,height = 5)

fig3 <- scHolography::scHolographyPlot(spatial.neighbor.Dermal$scHolography.obj,color.by = "spatial.neighborhood",color = fib.sp.col,cells = which(spatial.neighbor.Dermal$scHolography.obj$scHolography.sc$celltype%in%c("Dermal")))%>% plotly::layout(scene = scene)
plotly::orca(fig3, "3d.fib.alone.svg",width = 7,height = 5)

fig4 <- scHolography::scHolographyPlot(spatial.neighbor.Dermal$scHolography.obj,color.by = "spatial.neighborhood",color = fib.sp.col,cells = which(spatial.neighbor.Dermal$scHolography.obj$scHolography.sc$celltype%in%c("Dermal","Endothelial")))%>% plotly::layout(scene = scene)
plotly::orca(fig4, "3d.fib.endo.svg",width = 7,height = 5)

fig5 <- scHolography::scHolographyPlot(spatial.neighbor.Dermal$scHolography.obj,color.by = "celltype",cells = which(spatial.neighbor.Dermal$scHolography.obj$scHolography.sc$celltype%in%c("Basal","Dermal","Smooth Muscle")))%>% plotly::layout(scene = scene)
plotly::orca(fig5, "3d.fib.basal.derm.sm.og.type.svg",width = 7,height = 5)


fig1
fig2
fig3
fig4
fig5
```


```{r}
library(ggplot2)
tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human Skin/Fib.spatial.neighbor.heatmap.tiff", units="in", width=8, height=9, res=300)
DoHeatmap(spatial.neighbor.Dermal$bulk.count.obj,assay = "SCT", features = top10$gene,group.colors = brewer.pal(4,"Greens")) + NoLegend()+viridis::scale_fill_viridis()+theme(axis.text = element_text(size = 16,face = "bold"))
dev.off()
```

```{r}
library(RColorBrewer)
scene = list(camera = list(eye = list(x = -1, z = 0, y = 2)))

fib1 <- scHolography::scHolographyPlot(spatial.neighbor.Dermal$scHolography.obj,color.by = "spatial.neighborhood",color = fib.sp.col,cells = which(spatial.neighbor.Dermal$scHolography.obj$scHolography.sc$celltype%in%c("Basal","Dermal","Endothelial","Smooth Muscle")))%>% plotly::layout(scene = scene)
plotly::orca(fib1, "3d.fib.svg",width = 7,height = 5)

fib1
```



```{r}
fib1234 <- spatial.neighbor.Dermal$query.only.obj$scHolography.sc
fib1234$spatial.neighborhood <-paste0("Dermal_",fib1234$spatial.neighborhood)
fib1234$spatial.neighborhood <- factor(fib1234$spatial.neighborhood ,levels = sort(unique(fib1234$spatial.neighborhood )))
fib1234 <- SetIdent(fib1234,value ="spatial.neighborhood")

tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human Skin/Fib.peri.vln.mark.plot.tiff", units="in", width=5, height=5, res=300)
VlnPlot(fib1234,c("RGS5","NOTCH3","MYH11","ACTA2"),assay = "SCT",ncol = 2,cols = (brewer.pal(4,"Greens")))
dev.off()

tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human Skin/Fib.1234.col.vln.mark.plot.tiff", units="in", width=5, height=2.5, res=300)
VlnPlot(fib1234,c("COL1A2","DCN"),assay = "SCT",ncol = 2,cols = (brewer.pal(4,"Greens")))
dev.off()

```
```{r}
tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human Skin/Fib.1234.four.stack.vln.mark.plot.tiff", units="in", width=5, height=6, res=600)
VlnPlot(fib1234,c("APCDD1","TWIST2","ADH1B","GREM1","ABCA8","IGF1","RGS5","NOTCH3"),assay = "SCT",stack = T,flip = T)+NoLegend()+theme(axis.text = element_text(size = 16,face = "bold"),axis.title.x = element_blank(),axis.title.y = element_text(size = 16,face = "bold") ,axis.text.x = element_text(angle = 30,hjust=1))+scale_fill_manual(values = c("#EDF8E9","#EDF8E9", "#BAE4B3" ,"#BAE4B3" ,"#74C476","#74C476", "#238B45", "#238B45"))
dev.off()
```

```{r}
library(ggpubr)
my_comparisons <- list( c("Dermal_1", "Dermal_2"), c("Dermal_2", "Dermal_3"), c("Dermal_3", "Dermal_4") )

tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_3rdDraft//clusterDist.Fib1.2.3.4.to.4_rev.tiff", units="in", width=5, height=5, res=600)
scHolography::clusterDistanceBoxplot(spatial.neighbor.Dermal$scHolography.obj,annotationToUse = "spatial.neighborhood",query.cluster.list = (paste0("Dermal_",c(1:4))),reference.cluster = c("Dermal_4"))+ggplot2::scale_fill_manual(values = (brewer.pal(4,"Greens"))[1:4])+ 
  geom_signif(comparisons = my_comparisons,test.args = list(size=5),map_signif_level = TRUE)+NoLegend()+theme(axis.text = element_text(size = 16,face = "bold"),axis.title.x = element_blank(),axis.title.y = element_text(size = 20,face = "bold") ,axis.text.x = element_text(angle = 45,hjust=1))+ylab("SMN Distance")
dev.off()


```

```{r}
dyn.fib <-findGeneSpatialDynamics(spatial.neighbor.Dermal$scHolography.obj,query.cluster = paste0("Dermal_",c(1:3)),ref.cluster = c("Smooth Muscle"),annotationToUse = "spatial.neighborhood",assayToUse = "SCT")
spatialDynamicsFeaturePlot(spatial.neighbor.Dermal$scHolography.obj,query.cluster = paste0("Dermal_",c(1:3)),ref.cluster = c("Smooth Muscle"),annotationToUse = "spatial.neighborhood",geneOI = c(head(dyn.fib)$gene,tail(dyn.fib)$gene),assayToUse = "SCT")
```

```{r}

tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human Skin/Fib.spatial.neighbor.1-4.dyn.heat.tiff", units="in", width=12, height=8, res=300)
spatialDynamicsFeaturePlot(spatial.neighbor.Dermal$scHolography.obj,query.cluster=paste0("Dermal_",1:4),ref.cluster = c("Dermal_4"),annotationToUse = "spatial.neighborhood",geneOI = c("APCDD1","TWIST2","WNT5A","POSTN","SFRP2","GREM1","ADH1B","IGF1","ABCA8","CXCL12","MFAP5","RGS5","NOTCH3","ACTA2","MYH11"),assayToUse = "SCT",self.color = c((colorRampPalette(brewer.pal(12,"Paired"))(10)[1]),(brewer.pal(4,"Greens")),(colorRampPalette(brewer.pal(12,"Paired"))(10)[3:10])))
dev.off()
```


```{r}
tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human Skin/Fib.spatial.neighbor.distal.col6a5.tiff", units="in", width=5, height=4, res=300)
expressionByDistPlot(spatial.neighbor.Dermal$scHolography.obj,query.cluster=paste0("Dermal_",1:3),ref.cluster = c("Smooth Muscle"),annotationToUse = "spatial.neighborhood",geneOI = "COL6A5",assayToUse = "SCT")
dev.off()

tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human Skin/Fib.spatial.neighbor.proximal.mfap5.tiff", units="in", width=5, height=4, res=300)
expressionByDistPlot(spatial.neighbor.Dermal$scHolography.obj,query.cluster=paste0("Dermal_",1:3),ref.cluster = c("Smooth Muscle"),annotationToUse = "spatial.neighborhood",geneOI = "MFAP5",assayToUse = "SCT")
dev.off()
```

```{r}
fib.sub <- spatial.neighbor.Dermal$scHolography.obj$scHolography.sc

tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human Skin//dermal.spatial.cluster.tiff", units="in", width=4, height=4, res=300)
DimPlot(fib.sub,group.by = "spatial.neighborhood",reduction = "ind.umap",cells = which(fib.sub$celltype%in%"Dermal"))+ggtitle("Spatial Neighborhoods")+scale_colour_manual(values = brewer.pal(4,"Greens"))+NoLegend()
dev.off()

tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human Skin//dermal.seurat.cluster.tiff", units="in", width=4, height=4, res=300)
DimPlot(fib.sub,group.by = "orig.cluster",reduction = "ind.umap",cells = which(fib.sub$celltype%in%"Dermal"))+ggtitle("Seurat Cluster")+scale_color_brewer(palette = "Set1")+NoLegend()
dev.off()
```

