---
title: "R Notebook"
output: html_notebook
---
```{r}
library(scHolography)
```


# scHolography Analysis
```{r}
P6_rep1.obj<-readRDS("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Spatial Transcriptomics/PK Data/P6_rep1.obj.rds")
P6<-readRDS("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Spatial Transcriptomics/PK Data//P6.rds")
scSCC.meta <- read.table("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Data/human/sc_squamous cell carcinoma/GSE144236_patient_metadata_new.txt",sep="\t")
options(future.globals.maxSize = 3000 * 1024^2)
celltype <- names(table(P6$level2_celltype))
P6.sub <- subset(P6, cells = which(P6$level2_celltype%in%celltype[-which(celltype%in%c("Keratinocyte","Multiplet"))]))
sp.integrated <- dataAlign(low.res.sp =  P6_rep1.obj,high.res.sp =  P6.sub,nPCtoUse = 32)
SCC.obj<-trainHolography(sp.integrated,n.repeat = 30)
```

```{r}
SCC.obj <- readRDS("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC/scholography.obj.rds")
```

```{r}
library(Seurat)
library(ggplot2)
P6.sub<- subset(P6, cells = which(P6$level2_celltype%in%celltype[-which(celltype%in%c("Keratinocyte","Multiplet"))]))
P6<-P6.sub 
P6$level2_celltype<-factor(P6$level2_celltype)

P6@active.ident<-P6$level2_celltype
P6_rep1.obj<-SCTransform(P6_rep1.obj,assay = "Spatial")
P6 <- SCTransform(P6)
P6_rep1.obj<-RunPCA(P6_rep1.obj)
P6 <- RunPCA(P6)
P6_rep1.obj<-RunUMAP(P6_rep1.obj,dims = 1:30)
P6 <- RunUMAP(P6,dims = 1:30)
P6_rep1.obj<-FindNeighbors(P6_rep1.obj,dims = 1:30)
P6 <- FindNeighbors(P6,dims = 1:30)
P6_rep1.obj<-FindClusters(P6_rep1.obj)
P6 <- FindClusters(P6)

P6$my.level <- as.character(P6$level2_celltype)
P6$my.level[which(P6$my.level%in%c("Mac","ASDC","CD1C","CLEC9A","LC","MDSC","PDC"))] <- "Myeloid"

og.color <- colorRampPalette( RColorBrewer::brewer.pal(12,"Set1"))(length(unique(P6$my.level)))

tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC/scSCC(no legend).tiff", units="in", width=6, height=6, res=300)
DimPlot(P6,group.by = "my.level",cols = og.color,pt.size = 0.75)+ggtitle("")+NoLegend()
dev.off()
tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC/stSCC.tiff", units="in", width=6, height=4, res=300)
SpatialDimPlot(P6_rep1.obj,image.alpha = 0.5)
dev.off()
```

```{r}
scHolographyPlot(SCC.obj)
scHolographyPlot(SCC.obj,color.by = "Disease")
scHolographyPlot(SCC.obj,color.by = "level2_celltype",palette = "Set1")
SCC.obj$scHolography.sc$level3_celltype <-scSCC.meta[colnames(SCC.obj$scHolography.sc),"level3_celltype"]
scHolographyPlot(SCC.obj,color.by = "level3_celltype",palette = "Set1")


SCC.obj$scHolography.sc$my.level <- SCC.obj$scHolography.sc$level2_celltype
SCC.obj$scHolography.sc$my.level[which(SCC.obj$scHolography.sc$my.level%in%c("Mac","ASDC","CD1C","CLEC9A","LC","MDSC","PDC"))] <- "Myeloid"


temp <- SCC.obj$scHolography.sc$x3d_sp
SCC.obj$scHolography.sc$x3d_sp <- -SCC.obj$scHolography.sc$y3d_sp
SCC.obj$scHolography.sc$y3d_sp <-temp

library(dplyr)
scene = list(camera = list(eye = list(x = 0.2, y = 0, z = -2)))
my.col <- (og.color)[-c(2,5)]
fig1 <- (scHolographyPlot(SCC.obj,color.by = "my.level",color = my.col)%>% plotly::layout(scene = scene) )

fig2 <- scHolographyPlot(SCC.obj,color.by = "Disease")%>% plotly::layout(scene = scene) 
fig1
fig2
plotly::orca(fig1, "3dct.svg",width = 7,height = 5)
plotly::orca(fig2, "3ddisease.svg")
```
```{r}
micro.env <- scHolography::scHolographyNeighborCompPlot(SCC.obj,annotationToUse ="my.level",query.cluster = c("Normal_KC_Basal" ,"Normal_KC_Cyc","Normal_KC_Diff" ,"TSK","Tumor_KC_Basal","Tumor_KC_Cyc","Tumor_KC_Diff"),color = my.col)
tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC//microenvironment.tiff", units="in", width=6, height=5, res=600)
micro.env$neighbor.comp.plot+ theme(axis.text.x = element_text(angle = 45, hjust=1))+theme(axis.title.x = element_blank(),axis.title.y = element_blank(),axis.text = element_text(size = 15,face = "bold"))+NoLegend()
dev.off()
```


```{r}
library(ggpubr)
my_comparisons <- list( c("TSK", "Tumor_KC_Cyc"), c("Tumor_KC_Cyc", "Tumor_KC_Basal"), c("Tumor_KC_Basal", "Tumor_KC_Diff") )
#SCC.obj$scHolography.sc$tumor.k.n.normal <- SCC.obj$scHolography.sc$level2_celltype
#SCC.obj$scHolography.sc$tumor.k.n.normal[which(SCC.obj$scHolography.sc$Disease%in%"Normal")]

tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC//tumor.kc.to.tcell.dist.tiff", units="in", width=5, height=5, res=600)
clusterDistanceBoxplot(SCC.obj,annotationToUse = "my.level",query.cluster.list = c("TSK","Tumor_KC_Cyc","Tumor_KC_Basal","Tumor_KC_Diff"),reference.cluster = c("Tcell"))+ 
  stat_compare_means(comparisons = my_comparisons,method.args = list("less"))+scale_fill_manual(values = my.col[c(11,13,12,14)])+ theme(axis.text.x = element_text(angle = 45, hjust=1))+theme(axis.title.x = element_blank(),axis.text = element_text(size = 15,face = "bold"),axis.title = element_text(size = 15,face = "bold"))+NoLegend()
dev.off()

tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC//tumor.kc.to.myeloid.dist.tiff", units="in", width=5, height=5, res=600)
clusterDistanceBoxplot(SCC.obj,annotationToUse = "my.level",query.cluster.list = c("TSK","Tumor_KC_Cyc","Tumor_KC_Basal","Tumor_KC_Diff"),reference.cluster = c("Myeloid"))+ 
  stat_compare_means(comparisons = my_comparisons,method.args = list("less"))+scale_fill_manual(values = my.col[c(11,13,12,14)])+ theme(axis.text.x = element_text(angle = 45, hjust=1))+theme(axis.title.x = element_blank(),axis.text = element_text(size = 15,face = "bold"),axis.title = element_text(size = 15,face = "bold"))+NoLegend()
dev.off()
```



```{r}
scc.sp.neighbor.tumor_new <- findSpatialNeighborhood(SCC.obj,annotationToUse = "my.level",query.cluster = c("Tumor_KC_Basal","Tumor_KC_Cyc","Tumor_KC_Diff","TSK"),orig.assay = "RNA")


neighbor.comp <- scHolography::scHolographyNeighborCompPlot(scc.sp.neighbor.tumor_new$scHolography.obj,annotationToUse = "spatial.neighborhood",query.cluster = as.character(1:3))
neighbor.comp$neighbor.comp.plot
neighbor.comp$neighbor.comp.sig.plot
neighbor.comp$neighbor.comp.sig
library(dplyr)
scc.sp.neighbor.tumor_new$neighbor.marker %>%
  group_by(cluster) %>%
  top_n(n = 10, wt = avg_log2FC) -> top10
library(RColorBrewer)
tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC/TumorKC.spatial.neighbor.bulk.heatmap.tiff", units="in", width=8, height=9, res=600)
DoHeatmap(scc.sp.neighbor.tumor_new$bulk.count.obj,assay = "SCT", features = top10$gene,group.colors = (brewer.pal(3,"RdPu"))) + NoLegend()+viridis::scale_fill_viridis()+ NoLegend()+viridis::scale_fill_viridis()+theme(axis.text = element_text(size = 16,face = "bold"))
dev.off()

scc.sp.neighbor.tumor_new$sc.marker %>%
  group_by(cluster) %>%
  top_n(n = 10, wt = avg_log2FC) -> top10b

tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC/TumorKC.spatial.neighbor.sc.heatmap.tiff", units="in", width=8, height=9, res=600)
DoHeatmap(scc.sp.neighbor.tumor_new$query.only.obj$scHolography.sc,assay = "SCT", features = top10b$gene,group.by = "spatial.neighborhood",group.colors = (brewer.pal(3,"RdPu"))) + NoLegend()+viridis::scale_fill_viridis()+theme(axis.text = element_text(size = 16,face = "bold"))
dev.off()

```

```{r}
scc.sp.neighbor.tumor_new$query.only.obj$scHolography.sc$spatial.neighborhood <- paste0("Tumor_KC",scc.sp.neighbor.tumor_new$query.only.obj$scHolography.sc$spatial.neighborhood)
scc.sp.neighbor.tumor_new$query.only.obj$scHolography.sc <- SetIdent(scc.sp.neighbor.tumor_new$query.only.obj$scHolography.sc, value = "spatial.neighborhood")



tumor.kc.comp <- scc.sp.neighbor.tumor_new$query.only.obj$scHolography.sc@meta.data[,c("spatial.neighborhood","level2_celltype")]
tumor.kc.comp$level2_celltype <- factor(tumor.kc.comp$level2_celltype,levels = c("TSK","Tumor_KC_Cyc","Tumor_KC_Basal","Tumor_KC_Diff" ))

tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC/TumorKC.OG.cluster.composition.tiff", units="in", width=5, height=5, res=600)
ggplot(tumor.kc.comp, aes(fill=spatial.neighborhood, x=level2_celltype)) + 
  geom_bar(position="fill")+scale_fill_manual(values = brewer.pal(3,"RdPu"))+theme_classic()+ NoLegend()+theme(axis.text = element_text(size = 16,face = "bold"),axis.title.x = element_blank(),axis.title.y = element_blank(),axis.text.x = element_text(angle = 45, hjust=1))
dev.off()
```


```{r}
fig.sp.neighb <- scHolographyPlot(scc.sp.neighbor.tumor_new$scHolography.obj,cells = which(scc.sp.neighbor.tumor_new$scHolography.obj$scHolography.sc$level2_celltype%in%c("Tcell", "Tumor_KC_Basal","Tumor_KC_Cyc","Tumor_KC_Diff","TSK")), color.by = "spatial.neighborhood",color = c(brewer.pal(3,"RdPu"), my.col[-c(11:14)]))%>% plotly::layout(scene = scene) 
fig.sp.neighb
plotly::orca(fig.sp.neighb, "fig.sp.neighb.tumor.kc.svg")
```

```{r}
library(RColorBrewer)
my_comparisons <- list( c("1", "2"), c("2", "3") )

tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC/TumorKC.sp.neighb.dist.to.tcell.tiff", units="in", width=3, height=5, res=600)
clusterDistanceBoxplot(scc.sp.neighbor.tumor_new$scHolography.obj,annotationToUse = "spatial.neighborhood",query.cluster.list = as.character(c(1:3)),reference.cluster = "Tcell")+scale_fill_manual(values = (brewer.pal(3,"RdPu")))+ 
  stat_compare_means(comparisons = my_comparisons,method.args = list("greater"),size = 5)+theme(axis.text.x = element_text(angle = 45, hjust=1))+theme(axis.title.x = element_blank(),axis.text = element_text(size = 15,face = "bold"),axis.title = element_text(size = 15,face = "bold"))+NoLegend()+ scale_x_discrete(labels=c('Tumor_KC1', 'Tumor_KC2', 'Tumor_KC3'))
dev.off()


tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC/TumorKC.sp.neighb.dist.to.myeloid.tiff", units="in", width=3, height=5, res=600)
clusterDistanceBoxplot(scc.sp.neighbor.tumor_new$scHolography.obj,annotationToUse = "spatial.neighborhood",query.cluster.list = as.character(c(1:3)),reference.cluster = "Myeloid")+scale_fill_manual(values = (brewer.pal(3,"RdPu")))+ 
  stat_compare_means(comparisons = my_comparisons,method.args = list("greater"),size = 5)+theme(axis.text.x = element_text(angle = 45, hjust=1))+theme(axis.title.x = element_blank(),axis.text = element_text(size = 15,face = "bold"),axis.title = element_text(size = 15,face = "bold"))+NoLegend()+ scale_x_discrete(labels=c('Tumor_KC1', 'Tumor_KC2', 'Tumor_KC3'))
dev.off()
```
```{r}
tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC/TumorKC.sp.neighb.comp.tiff", units="in", width=4, height=5, res=600)
neighbor.comp$neighbor.comp.plot+scale_fill_manual(values = c(brewer.pal(3,"RdPu"), my.col[-c(11:14)]))+theme(axis.title.x = element_blank(),axis.text = element_text(size = 15,face = "bold"),axis.title = element_text(size = 15,face = "bold"))+NoLegend()
dev.off()
```

























#Myloeid
```{r}
scc.sp.neighbor.mac_new <- findSpatialNeighborhood(SCC.obj,annotationToUse = "level2_celltype",query.cluster = c("Mac","ASDC","CD1C","CLEC9A","LC","MDSC","PDC"),orig.assay = "RNA")


neighbor.comp <- scHolography::scHolographyNeighborCompPlot(scc.sp.neighbor.mac_new$scHolography.obj,annotationToUse = "spatial.neighborhood",query.cluster = as.character(1:3))
neighbor.comp$neighbor.comp.plot
neighbor.comp$neighbor.comp.sig.plot
neighbor.comp$neighbor.comp.sig
library(dplyr)
scc.sp.neighbor.mac_new$neighbor.marker %>%
  group_by(cluster) %>%
  top_n(n = 50, wt = avg_log2FC) -> top10

#tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC/Mac.spatial.neighbor.bulk.heatmap.tiff", units="in", width=8, height=9, res=600)
DoHeatmap(scc.sp.neighbor.mac_new$bulk.count.obj,assay = "SCT", features = top10$gene,group.colors = (brewer.pal(3,"RdPu"))) + NoLegend()+viridis::scale_fill_viridis()+ NoLegend()+viridis::scale_fill_viridis()+theme(axis.text = element_text(size = 16,face = "bold"))
#dev.off()

scc.sp.neighbor.mac_new$sc.marker %>%
  group_by(cluster) %>%
  top_n(n = 20, wt = avg_log2FC) -> top10b

#tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC/Mac.spatial.neighbor.sc.heatmap.tiff", units="in", width=8, height=9, res=600)
DoHeatmap(scc.sp.neighbor.mac_new$query.only.obj$scHolography.sc,assay = "SCT", features = top10b$gene,group.by = "spatial.neighborhood",group.colors = (brewer.pal(3,"RdPu"))) + NoLegend()+viridis::scale_fill_viridis()+theme(axis.text = element_text(size = 16,face = "bold"))
#dev.off()
```

```{r}
scHolographyPlot(scc.sp.neighbor.mac_new$scHolography.obj,color.by = "spatial.neighborhood")
```
```{r}
neighbor.comp$neighbor.comp.plot
neighbor.comp$neighbor.comp.sig.plot
neighbor.comp$neighbor.comp.sig
```
```{r}
scHolography::clusterDistanceBoxplot(scc.sp.neighbor.mac_new$scHolography.obj,annotationToUse = "spatial.neighborhood",query.cluster.list = c("1","2","3"),reference.cluster = c("Tumor_KC_Basal","Tumor_KC_Cyc","Tumor_KC_Diff","TSK"))
```
```{r}
scHolography::clusterDistanceBoxplot(scc.sp.neighbor.mac_new$scHolography.obj,annotationToUse = "spatial.neighborhood",query.cluster.list = c("1","2","3"),reference.cluster = c("Tcell"))
```

```{r}
t(table(scc.sp.neighbor.mac_new$query.only.obj$scHolography.sc$spatial.neighborhood,scc.sp.neighbor.mac_new$query.only.obj$scHolography.sc$level2_celltype))/colSums(table(scc.sp.neighbor.mac_new$query.only.obj$scHolography.sc$spatial.neighborhood,scc.sp.neighbor.mac_new$query.only.obj$scHolography.sc$level2_celltype))
```

```{r}
Myeloid.comp <- scc.sp.neighbor.mac_new$query.only.obj$scHolography.sc@meta.data[,c("spatial.neighborhood","level2_celltype")]

#tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC/Myeloid.OG.cluster.composition.tiff", units="in", width=5, height=5, res=600)
ggplot(Myeloid.comp, aes(fill=spatial.neighborhood, x=level2_celltype)) + 
  geom_bar(position="fill")+scale_fill_manual(values = brewer.pal(3,"RdPu"))+theme_classic()+theme(axis.text = element_text(size = 16,face = "bold"),axis.title.x = element_blank(),axis.title.y = element_blank(),axis.text.x = element_text(angle = 45, hjust=1))
#dev.off()
```
```{r}
m.ploting<-data.frame(dist.Tcell=findDistance(SCC.obj,query.cluster= c("Mac","ASDC","CD1C","CLEC9A","LC","MDSC","PDC"),ref.cluster = "Tcell",annotationToUse = "level2_celltype"),dist.TumorKC=findDistance(SCC.obj,query.cluster= c("Mac","ASDC","CD1C","CLEC9A","LC","MDSC","PDC"),ref.cluster = c("TSK","Tumor_KC_Basal","Tumor_KC_Cyc","Tumor_KC_Diff"),annotationToUse = "level2_celltype"),spatial.neighborhood=scc.sp.neighbor.mac_new$query.only.obj$scHolography.sc$spatial.neighborhood,celltype=scc.sp.neighbor.mac_new$query.only.obj$scHolography.sc$level2_celltype)

library(ggplot2)
library(ggpubr)
library(RColorBrewer)
ggplot(data = m.ploting, aes(x = dist.Tcell, y = dist.TumorKC)) +
  geom_jitter(aes(color=spatial.neighborhood)) +
  stat_cor(label.y = 5.5,size=6) +theme_classic()+ scale_color_manual(values = brewer.pal(3,"RdPu"))+ 
  geom_smooth(method = "lm",  formula = y ~ x) +NoLegend()+xlab("dist.Tcell")+ylab("dist.TumorKC")+theme(axis.text = element_text(size = 12,face = "bold"),axis.text.x = element_text(angle = 45,hjust=1),axis.title=element_text(size = 15,face = "bold"))

Mac.color <- RColorBrewer::brewer.pal(12,"Accent")[1:length(unique(m.ploting$celltype))]


tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC/Myeloid.dotplot.tiff", units="in", width=6, height=6, res=600)
ggplot(data = m.ploting, aes(x = dist.Tcell, y = dist.TumorKC)) +
  geom_jitter(aes(color=celltype)) +
  stat_cor(label.y = 5.5,size=6) +theme_classic()+ 
  geom_smooth(method = "lm",  formula = y ~ x) +xlab("SMN Distance to T Cell")+ylab("SMN Distance to Tumor Keratinocyte")+theme(axis.text = element_text(size = 12,face = "bold"),axis.text.x = element_text(angle = 45,hjust=1),axis.title=element_text(size = 15,face = "bold"))+scale_color_manual(values = Mac.color)
dev.off()

```
```{r}

for (i in c("ASDC","CD1C","CLEC9A","LC","Mac","MDSC","PDC")) {
  tiff(paste0(paste0("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC/Myeloid.dotplot.",i),".tiff"), units="in", width=3, height=3, res=600)
  plot<-ggplot(data = m.ploting[which(m.ploting$celltype%in%i),], aes(x = dist.Tcell, y = dist.TumorKC)) +
    geom_jitter(aes(color=celltype)) +
    stat_cor(label.y = 5.5,size=6) +theme_classic() +xlab("SMN Distance to T Cell")+ylab("SMN Distance to Tumor Keratinocyte")+theme(axis.text = element_text(size = 10,face = "bold"),axis.text.x = element_text(angle = 45,hjust=1),axis.title=element_text(size = 10,face = "bold"),plot.title = element_text(hjust = 0.5,size = 16,face = "bold"),legend.position="none")+scale_color_manual(values = Mac.color[which(c("ASDC","CD1C","CLEC9A","LC","Mac","MDSC","PDC")%in%i)])+xlim(c(1,5))+ylim(c(1.25,5.25))+ggtitle(as.character(i))
  show(plot)
  dev.off()
}

```



```{r}
tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC/Myeloid.dist.to.tumor.kc.tiff", units="in", width=6, height=6, res=600)
clusterDistanceBoxplot(SCC.obj,annotationToUse = "level2_celltype",query.cluster.list =c("PDC","CLEC9A","ASDC","CD1C","LC","Mac","MDSC"),reference.cluster = c("TSK","Tumor_KC_Basal","Tumor_KC_Cyc","Tumor_KC_Diff") )+scale_fill_manual(values = Mac.color[c(7,3,1,2,4,5,6)])+ylab("SMN Distance to Tumor Keratinocyte")+theme(axis.text = element_text(size = 14,face = "bold"),axis.text.x = element_text(angle = 45,hjust=1),axis.title=element_text(size = 15,face = "bold"))+NoLegend()+xlab("")
dev.off()
```
```{r}
tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC/Myeloid.dist.to.tcell.tiff", units="in", width=6, height=6, res=600)
clusterDistanceBoxplot(scc.sp.neighbor.mac_new$scHolography.obj,annotationToUse = "level2_celltype",query.cluster.list =c("PDC","ASDC","CLEC9A","CD1C","Mac","MDSC","LC"),reference.cluster = "Tcell" )+scale_fill_manual(values = Mac.color[c(7,1,3,2,5,6,4)])+ylab("SMN Distance to T Cell")+theme(axis.text = element_text(size = 14,face = "bold"),axis.text.x = element_text(angle = 45,hjust=1),axis.title=element_text(size = 15,face = "bold"))+NoLegend()+xlab("")
dev.off()
```

```{r}
cur <- SCC.obj$scHolography.sc
cur <- SetIdent(cur,value = "level2_celltype")
find.all.top10 <- FindAllMarkers(cur,assay = "RNA")
find.all.top10.top <-find.all.top10 %>%
  group_by(cluster)



P6_rep1.obj<- AddModuleScore(P6_rep1.obj,features = list((find.all.top10.top%>%filter(cluster=="PDC")%>%filter(p_val_adj<0.05))$gene),assay = "SCT",name = "PDC")
P6_rep1.obj<- AddModuleScore(P6_rep1.obj,features = list((find.all.top10.top%>%filter(cluster=="ASDC")%>%filter(p_val_adj<0.05))$gene),assay = "SCT",name = "ASDC")
P6_rep1.obj<- AddModuleScore(P6_rep1.obj,features = list((find.all.top10.top%>%filter(cluster=="CLEC9A")%>%filter(p_val_adj<0.05))$gene),assay = "SCT",name = "CLEC9A")
P6_rep1.obj<- AddModuleScore(P6_rep1.obj,features = list((find.all.top10.top%>%filter(cluster=="Tcell")%>%filter(p_val_adj<0.05))$gene),assay = "SCT",name = "Tcell")

SpatialFeaturePlot(P6_rep1.obj,"CD3D")

```



```{r}
library(CellChat)
runCellChat <- function(cellchat.obj){
  CellChatDB <- CellChatDB.human
  CellChatDB.use <- CellChatDB 
  cellchat.obj@DB <- CellChatDB.use
  cellchat.obj <- subsetData(cellchat.obj)
  cellchat.obj <- identifyOverExpressedGenes(cellchat.obj)
  cellchat.obj <- identifyOverExpressedInteractions(cellchat.obj)
  cellchat.obj <- computeCommunProb(cellchat.obj)
  # Filter out the cell-cell communication if there are only few number of cells in certain cell groups
  cellchat.obj <- filterCommunication(cellchat.obj, min.cells = 10)
  cellchat.obj <- computeCommunProbPathway(cellchat.obj)
  cellchat.obj <- aggregateNet(cellchat.obj)
  cellchat.obj <- netAnalysis_computeCentrality(cellchat.obj, slot.name = "netP") 
  cellchat.obj
}


```

```{r}

SCC.obj$scHolography.sc$KC.proxi <- paste0(SCC.obj$scHolography.sc$level2_celltype,"_distal")
SCC.obj$scHolography.sc$KC.proxi[union(which(SCC.obj$scHolography.sc$level2_celltype%in%c("Tumor_KC_Basal","Tumor_KC_Cyc","Tumor_KC_Diff","TSK")),which(colSums((SCC.obj$adj.mtx[which(SCC.obj$scHolography.sc$level2_celltype%in%c("Tumor_KC_Basal","Tumor_KC_Cyc","Tumor_KC_Diff","TSK")),]))>0))]   <-  paste0(SCC.obj$scHolography.sc$level2_celltype[union(which(SCC.obj$scHolography.sc$level2_celltype%in%c("Tumor_KC_Basal","Tumor_KC_Cyc","Tumor_KC_Diff","TSK")),which(colSums((SCC.obj$adj.mtx[which(SCC.obj$scHolography.sc$level2_celltype%in%c("Tumor_KC_Basal","Tumor_KC_Cyc","Tumor_KC_Diff","TSK")),]))>0))],"_proximal")



cellchat.obj.tumor.KC<- createCellChat(SCC.obj$scHolography.sc ,group.by = "KC.proxi",assay = "SCT")

cellchat.obj.tumor.KC <- runCellChat(cellchat.obj.tumor.KC)

cellchat.obj.tumor.KC.sub.chat <-cellchat.obj.tumor.KC@netP$prob[c(paste0(unlist(lapply(sort(unique(SCC.obj$scHolography.sc$KC.proxi)), function(x)  paste0(unlist(strsplit(x,split = "_"))[-length(unlist(strsplit(x,split = "_")))],collapse = "_")))[duplicated(unlist(lapply(sort(unique(SCC.obj$scHolography.sc$KC.proxi)), function(x)  paste0(unlist(strsplit(x,split = "_"))[-length(unlist(strsplit(x,split = "_")))],collapse = "_"))))],"_distal"),paste0(unlist(lapply(sort(unique(SCC.obj$scHolography.sc$KC.proxi)), function(x)  paste0(unlist(strsplit(x,split = "_"))[-length(unlist(strsplit(x,split = "_")))],collapse = "_")))[duplicated(unlist(lapply(sort(unique(SCC.obj$scHolography.sc$KC.proxi)), function(x)  paste0(unlist(strsplit(x,split = "_"))[-length(unlist(strsplit(x,split = "_")))],collapse = "_"))))],"_proximal")),c(paste0(unlist(lapply(sort(unique(SCC.obj$scHolography.sc$KC.proxi)), function(x)  paste0(unlist(strsplit(x,split = "_"))[-length(unlist(strsplit(x,split = "_")))],collapse = "_")))[duplicated(unlist(lapply(sort(unique(SCC.obj$scHolography.sc$KC.proxi)), function(x)  paste0(unlist(strsplit(x,split = "_"))[-length(unlist(strsplit(x,split = "_")))],collapse = "_"))))],"_distal"),paste0(unlist(lapply(sort(unique(SCC.obj$scHolography.sc$KC.proxi)), function(x)  paste0(unlist(strsplit(x,split = "_"))[-length(unlist(strsplit(x,split = "_")))],collapse = "_")))[duplicated(unlist(lapply(sort(unique(SCC.obj$scHolography.sc$KC.proxi)), function(x)  paste0(unlist(strsplit(x,split = "_"))[-length(unlist(strsplit(x,split = "_")))],collapse = "_"))))],"_proximal")),] 

cellchat.obj.tumor.KC.sub.chat.df <-reshape2::melt(cellchat.obj.tumor.KC.sub.chat)
netAnalysis_signalingRole_scatter(cellchat.obj.tumor.KC)
netAnalysis_signalingRole_heatmap(cellchat.obj.tumor.KC, pattern = "outgoing",color.heatmap = "YlOrRd",width = 15,height = 20)
netAnalysis_signalingRole_heatmap(cellchat.obj.tumor.KC, pattern = "incoming",color.heatmap = "YlOrRd",width = 15,height = 20)
signaling.to.plot <- c("MHC-II","CD99","THBS","ITGB2","CXCL","TNF","CCL","ICAM","EGF","EPHA","NOTCH","CD46","TWEAK","CDH","CDH1","MHC-I","JAM","IL16","IFN-II","CLEC","EPHB","CD6","CD86","FGF","CD45","CD80","IL1","CD70","TGFb","IL2","CD39","PDGF","CDH5","IGF","PD-L1","FLT3","BMP","PDL2","CLDN")
signaling.to.plot <- c("MHC-II","MHC-I","IL16","IFN-II","CD6","CD80","IL1","CD70","TGFb","PD-L1","PDL2")
tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC/TumorKC_firstDneighbor_sub.tiff", units="in", width=13, height=7, res=600)
netAnalysis_signalingRole_heatmap(cellchat.obj.tumor.KC, pattern = "all",width = 12,height = 6,signaling = signaling.to.plot,font.size = 10)
dev.off()

tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC/TumorKC_firstDneighbor.tiff", units="in", width=15, height=15, res=600)
netAnalysis_signalingRole_heatmap(cellchat.obj.tumor.KC, pattern = "all",width = 12,height = 12,font.size = 9)
dev.off()
```




























































```{r}
scHolography.obj <-SCC.obj
graph <- igraph::graph_from_adjacency_matrix(scHolography.obj$adj.mtx,
                                             mode = "undirected")
dist <- igraph::distances(graph, mode = "out")
scHolography.obj$scHolography.sc$level2_celltype <- factor(scHolography.obj$scHolography.sc$level2_celltype)

new.cluster.mat<- matrix(ncol=length(levels(scHolography.obj$scHolography.sc$level2_celltype)),nrow=length(levels(scHolography.obj$scHolography.sc$level2_celltype)))
colnames(new.cluster.mat) <- levels(scHolography.obj$scHolography.sc$level2_celltype)
rownames(new.cluster.mat) <- levels(scHolography.obj$scHolography.sc$level2_celltype)

for (i in levels(scHolography.obj$scHolography.sc$level2_celltype)) {
  for (j in levels(scHolography.obj$scHolography.sc$level2_celltype)) {
    new.cluster.mat[i,j] <- mean(dist[which(scHolography.obj$scHolography.sc$level2_celltype%in%i),which(scHolography.obj$scHolography.sc$level2_celltype%in%j)])
  }
  
}
library(dendextend)
dend<- as.dendrogram(hclust(as.dist(new.cluster.mat)))
plot(dend)
clus.order <- c("Fibroblast","Eccrine","Melanocyte","Endothelial Cell","B Cell","NK","Tcell","Mac" ,"CLEC9A","MDSC", "CD1C","LC","ASDC" ,"PDC","Pilosebaceous","Normal_KC_Basal" ,"Normal_KC_Cyc","Normal_KC_Diff" ,"Tumor_KC_Basal","Tumor_KC_Cyc","Tumor_KC_Diff","TSK")
```


```{r}

scHolography.obj <- SCC.obj
annotationToUse <- "level2_celltype"

clus <- scHolography.obj$scHolography.sc[[annotationToUse]][[1]]
query.cluster <- stringr::str_sort(unique(clus),numeric = T)
uni.clus <- unique(clus)
matrix <- matrix(ncol = length(unique(clus)),nrow = length(query.cluster), 0)
colnames(matrix) <-stringr::str_sort(unique(clus),numeric = T)
rownames(matrix) <- query.cluster

for (i in query.cluster) {
  ind <- which(clus==i)
  tab <- table(clus[which(colSums(scHolography.obj$adj.mtx[ind,])>0)])
  matrix[i,names(tab)] <- tab
}
data.fra <- reshape2::melt(matrix/rowSums(matrix))

library(ggplot2)

getPalette = colorRampPalette(brewer.pal(9, "Set1"))
data.fra$Var1 <- factor(data.fra$Var1,levels = clus.order)
tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC/microenvironment.tiff", units="in", width=10, height=6, res=600)
ggplot(data.fra, aes(x=Var1, y=value,fill=Var2))+ geom_bar( position="stack", stat="identity")+theme_classic()+ 
  theme(axis.text.x = element_text(angle=45, hjust=1))+scale_fill_manual(values = getPalette(length(uni.clus)))
dev.off()

```
```{r}
#query.cluster <- list(c("Normal_KC_Basal","Normal_KC_Cyc","Normal_KC_Diff"),c("Tumor_KC_Basal","Tumor_KC_Cyc","Tumor_KC_Diff","TSK"))

scHolography.obj <- SCC.obj
annotationToUse <- "level2_celltype"
clus <- scHolography.obj$scHolography.sc[[annotationToUse]][[1]]
uni.clus <- stringr::str_sort(unique(clus),numeric = T)

sig.class.ls <- lapply(uni.clus, function(ind.clus){
  
  query.cluster <- list(c(ind.clus),uni.clus[-which(uni.clus%in%c(ind.clus))])
  matrix.ls <-vector("list",2)
  
  for (i in 1:2) {
    ind <- which(clus%in%query.cluster[[i]])
    
    matrix.this<- matrix(unlist(lapply(uni.clus, function(x){
      this.clus <- which(clus==x)
      rowSums(scHolography.obj$adj.mtx[,this.clus])
    })),ncol=length(uni.clus),byrow=F)
    colnames(matrix.this) <- uni.clus
    matrix.ls[[i]] <- matrix.this[ind,]
    
  }
  
  pval.ls <- lapply(uni.clus,function(x){
    wilcox.test(matrix.ls[[1]][,x],matrix.ls[[2]][,x],alternative="greater")$p.value
  })
  names(pval.ls) <- uni.clus
  unlist(pval.ls)[names(which(unlist(pval.ls)>=.05))]
})

names(sig.class.ls) <- uni.clus
sig.class.ls


```
```{r}
norm.mat <- matrix/rowSums(matrix)
for(i in uni.clus){
  norm.mat[i,names(sig.class.ls[[i]])] <- 0
}

data.fra.sig <- reshape2::melt(norm.mat)
getPalette = colorRampPalette(brewer.pal(9, "Set1"))
data.fra.sig$Var1 <- factor(data.fra.sig$Var1, levels = clus.order)
tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC/microenvironment.sig.tiff", units="in", width=16, height=6, res=600)
ggplot(data.fra.sig, aes(x=Var1, y=value,fill=Var2))+ geom_bar( position="stack", stat="identity")+theme_classic()+ 
  theme(axis.text.x = element_text(angle=45, hjust=1))+scale_fill_manual(values = getPalette(length(uni.clus)))
dev.off()
```

```{r}
tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC/microenvironment.sig.KC.tiff", units="in", width=8, height=6, res=600)
ggplot(data.fra.sig[which(data.fra.sig$Var1%in%c("Normal_KC_Basal","Normal_KC_Cyc","Normal_KC_Diff","Tumor_KC_Basal","Tumor_KC_Cyc","Tumor_KC_Diff","TSK")),], aes(x=Var1, y=value,fill=Var2))+ geom_bar( position="stack", stat="identity")+theme_classic()+ 
  theme(axis.text.x = element_text(angle=45, hjust=1))+scale_fill_manual(values = getPalette(length(uni.clus)))
dev.off()
```



```{r}

scHolography.obj <- SCC.obj
annotationToUse <- "level2_celltype"
clus <- scHolography.obj$scHolography.sc[[annotationToUse]][[1]]
uni.clus <- stringr::str_sort(unique(clus),numeric = T)

sig.class.ls <- lapply(uni.clus, function(ind.clus){
  
  query.cluster <- list(c(ind.clus),uni.clus[-which(uni.clus%in%c(ind.clus))])
  matrix.ls <-vector("list",2)
  
  for (i in 1:2) {
    ind <- which(clus%in%query.cluster[[i]])
    
    matrix.this<- matrix(unlist(lapply(uni.clus, function(x){
      this.clus <- which(clus==x)
      rowSums(scHolography.obj$adj.mtx[,this.clus])
    })),ncol=length(uni.clus),byrow=F)
    colnames(matrix.this) <- uni.clus
    matrix.ls[[i]] <- matrix.this[ind,]
    
  }
  
  pval.ls <- lapply(uni.clus,function(x){
    wilcox.test(matrix.ls[[1]][,x],matrix.ls[[2]][,x],alternative="greater")$p.value
  })
  names(pval.ls) <- uni.clus
  unlist(pval.ls)[names(which(unlist(pval.ls)<.05))]
})

names(sig.class.ls) <- uni.clus
sig.class.ls
```

```{r}
library(ggpubr)
my_comparisons <- list( c("Normal_KC_Diff", "Tumor_KC_Diff"), c("Normal_KC_Basal", "Tumor_KC_Basal"), c("Normal_KC_Cyc", "Tumor_KC_Cyc") )

tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC/kcDistancetoTcell.tiff", units="in", width=5, height=4, res=600)
clusterDistanceBoxplot(SCC.obj,query.cluster.list = c("Normal_KC_Diff","Normal_KC_Basal","Normal_KC_Cyc","Tumor_KC_Diff","Tumor_KC_Basal","Tumor_KC_Cyc","TSK"),reference.cluster = "Tcell",annotationToUse = "level2_celltype",palette = "Set1")+ 
  theme(axis.text.x = element_text(angle=45, hjust=1))+ 
  stat_compare_means(comparisons = my_comparisons)
dev.off()
```
```{r}
# dist.to.tsk <- lapply(uni.clus,function(x){
#   median(findDistance(SCC.obj,query.cluster = x,ref.cluster = "TSK",annotationToUse = "level2_celltype"))
# })
# names(dist.to.tsk) <- uni.clus
# sort(unlist(dist.to.tsk))
```





```{r}
SCC.obj.kc.sub <- SCC.obj
SCC.obj.kc.sub$scHolography.sc <- subset(SCC.obj.kc.sub$scHolography.sc,cells = which(SCC.obj.kc.sub$scHolography.sc$level2_celltype%in%c("Normal_KC_Basal","Normal_KC_Cyc","Normal_KC_Diff","Tumor_KC_Basal","Tumor_KC_Cyc","Tumor_KC_Diff","TSK","Tcell")))
SCC.obj.kc.sub$scHolography.sc[["TcellInf"]] <- SCC.obj.kc.sub$scHolography.sc$Disease
SCC.obj.kc.sub$scHolography.sc[["TcellInf"]][[1]][which(SCC.obj.kc.sub$scHolography.sc$level2_celltype=="Tcell")] <- "Tcell" 
fig <- scHolographyPlot(SCC.obj.kc.sub,color.by = "TcellInf")%>% plotly::layout(scene = scene) 
fig
plotly::orca(fig, "TcellInf.svg")

```

```{r}
scHolography.obj <- SCC.obj

scHolography.obj$scHolography.sc[["disease.tsk"]] <- scHolography.obj$scHolography.sc$level2_celltype
scHolography.obj$scHolography.sc[["disease.tsk"]] [[1]][which(scHolography.obj$scHolography.sc$level2_celltype%in%c("Normal_KC_Basal","Normal_KC_Cyc","Normal_KC_Diff"))] <- "Normal_KC"
scHolography.obj$scHolography.sc[["disease.tsk"]] [[1]][which(scHolography.obj$scHolography.sc$level2_celltype%in%c("TSK"))] <- "TSK"
scHolography.obj$scHolography.sc[["disease.tsk"]] [[1]][which(scHolography.obj$scHolography.sc$level2_celltype%in%c("Tumor_KC_Basal","Tumor_KC_Cyc","Tumor_KC_Diff"))] <- "Tumor_KC"

annotationToUse <- "disease.tsk"
query.cluster <- c("Normal_KC","Tumor_KC","TSK")


#annotationToUse <- "level2_celltype"
#query.cluster <- c("Normal_KC_Basal","Normal_KC_Cyc","Normal_KC_Diff","Tumor_KC_Basal","Tumor_KC_Cyc","Tumor_KC_Diff","TSK")


scHolography.sc <- scHolography.obj$scHolography.sc
all.ind<-c()
cluster<-c()
obj.ls <- vector(mode="list", length = length(query.cluster))
names(obj.ls) <- query.cluster
for (i in query.cluster) {
  this.ind <- which(scHolography.sc[[annotationToUse]][[1]]%in%i)
  neighbor.ind <- which(colSums(scHolography.obj$adj.mtx[this.ind,])>0)
  all.ind <- c(all.ind,neighbor.ind)
  cluster<-c(cluster, rep(i, length(neighbor.ind)))
  neighb <- subset(scHolography.sc,cells = neighbor.ind)
  neighb <- RenameCells(
    object = neighb,
    new.names = paste(i,colnames(neighb),sep = "_"))
  
  
  obj.ls[[i]] <- neighb
}

neighbor.obj <- scCustomize::Merge_Seurat_List(list_seurat = obj.ls)
neighbor.obj[["neighbor"]] <- factor(cluster)
neighbor.obj <- SetIdent(neighbor.obj, value = "neighbor")

feature.neighbor <- FindAllMarkers(neighbor.obj, assay = "RNA")
```
```{r}
library(dplyr)
DefaultAssay(neighbor.obj) <- "RNA"
neighbor.obj <- NormalizeData(neighbor.obj)
neighbor.obj <- ScaleData(neighbor.obj)


feature.neighbor %>%
  group_by(cluster) %>%
  top_n(n = 10, wt = avg_log2FC) -> top10
DoHeatmap(neighbor.obj, features = top10$gene,assay = "RNA") + NoLegend()
tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Human SCC/TSK environment genes.tiff", units="in", width=5.5, height=6.5, res=600)
DotPlot(object = neighbor.obj,  features = unique(top10$gene),assay = "RNA")+ 
  theme(axis.text.x = element_text(angle=45, hjust=1))+coord_flip()+viridis::scale_color_viridis()
dev.off()
```

```{r}
scHolography.obj.sub <-scHolography.obj
scHolography.obj.sub$scHolography.sc <- subset(scHolography.obj.sub$scHolography.sc, cells = which(scHolography.obj$scHolography.sc$disease.tsk%in%c("Normal_KC","Tumor_KC","TSK","Tcell")))
#scHolography.obj.sub$scHolography.sc <- subset(scHolography.obj.sub$scHolography.sc, cells = which(scHolography.obj$scHolography.sc$disease.tsk%in%c("Normal_KC","Tumor_KC","TSK","Tcell","ASDC","Eccrine","Fibroblast","LC","MDSC","Melanocyte","Pilosebaceous")))
scene = list(camera = list(eye = list(x = 0, y = -2, z = 0.25)))
fig <- scHolographyPlot(scHolography.obj.sub,color.by = "disease.tsk")%>% plotly::layout(scene = scene) 
fig
plotly::orca(fig, "Tcell.TSK.Inf.svg")
```

```{r}
fig <- scHolographyPlot(scHolography.obj.sub,feature = "SERPINB3")%>% plotly::layout(scene = scene) 
fig
plotly::orca(fig, "SERPINB3_Tcell.TSK.Inf.svg")
```

```{r}
fig <- scHolographyPlot(scHolography.obj.sub,feature = "ZFP36L2")%>% plotly::layout(scene = scene) 
fig
plotly::orca(fig, "ZFP36L2_Tcell.TSK.Inf.svg")
```

