---
title: "R Notebook"
output: html_notebook
---

```{r}
library(scHolography)
library(Seurat)
```
```{r}
ref <- readRDS("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus//mouse_hippocampus_reference.rds")
ref <- SCTransform(ref)

```

```{r}

visium <- Load10X_Spatial("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus/Visium/")
rownames(visium@assays$Spatial@data) <- toupper(rownames(visium@assays$Spatial@data))
rownames(visium@assays$Spatial@counts) <- toupper(rownames(visium@assays$Spatial@counts))
visium <- SCTransform(visium,assay = "Spatial")
visium <- RunPCA(visium,assay = "SCT")
visium <- FindNeighbors(visium, reduction = "pca")
visium <- FindClusters(visium, verbose = FALSE)
visium <- RunUMAP(visium, reduction = "pca", dims = 1:30)
DimPlot(visium)
SpatialDimPlot(visium,label = T)
```



```{r}
set.seed(60611)
ref.sub <- subset(ref, cells = sample(colnames(ref),8000))
sp.integrated.visium <- dataAlign(low.res.sp =  visium,high.res.sp =  ref.sub,stProcessed = T,future.size = 7000)
saveRDS(sp.integrated.visium,"~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus/sp.integrated.visium.rds")
hippo.brain.obj.visium<-trainHolography(sp.integrated.visium,n.repeat = 30)
hippo.brain.obj.visium <- readRDS("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus/scHolography.obj.rds")

temp <- hippo.brain.obj.visium$scHolography.sc$x3d_sp
hippo.brain.obj.visium$scHolography.sc$x3d_sp <- hippo.brain.obj.visium$scHolography.sc$z3d_sp
hippo.brain.obj.visium$scHolography.sc$z3d_sp <- temp

scene = list(camera = list(eye = list(x = 0, z = 0, y = 1.8)))

fig1 <- scHolographyPlot(hippo.brain.obj.visium,color.by = "celltype",cells = which(hippo.brain.obj.visium$scHolography.sc$celltype%in%c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells")),color = c(c("black",c("#d11141","#ffc425","#00aebd")),rep("black",15)))%>% plotly::layout(scene = scene)
fig1
plotly::orca(fig1, "hippo.CA123.svg",width = 4.5,height = 6)
```


```{r}

pca.obj<-hippo.brain.obj.visium$raw.prediction
ind <- which(colnames(ref.sub)%in%names(hippo.brain.obj.visium$scHolography.sc$celltype)[ which(hippo.brain.obj.visium$scHolography.sc$celltype%in%c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells"))])

library(plotly)
plot_ly( x = pca.obj[ind,1], y = pca.obj[ind,2], z = pca.obj[ind,3], color = hippo.brain.obj.visium$scHolography.sc$celltype[ which(hippo.brain.obj.visium$scHolography.sc$celltype%in%c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells"))], colors = c("#d11141","#ffc425","#00aebd"))

```



```{r}

a <- cbind(rownames(ref.sub@assays$RNA@counts),(as.matrix(ref.sub@assays$RNA@counts)))
colnames(a) <- paste("c",colnames(a),sep = "_")
colnames(a)[1] <- "GENES"
write.table(a,"~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus//expressionSC.txt",row.names = F,col.names = colnames(a),quote = F,sep = '\t')

b <- cbind(rownames(visium@assays$Spatial@counts),as.matrix(visium@assays$Spatial@counts))
colnames(b)[1] <- "GENES"
write.table(b,"~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus//expressionST.txt",row.names = F,col.names = colnames(b),quote = F,sep = '\t')

write.table(data.frame(SpotID=colnames(visium),row=visium@images$slice1@coordinates$imagerow,col=visium@images$slice1@coordinates$imagecol),"~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus//coordinateST.txt",quote = F,row.names = F,sep = '\t')

write.table(data.frame(Cell_IDs=paste("c",colnames((as.matrix(ref.sub@assays$RNA@counts))),sep = "_"),CellType=as.character(ref.sub$celltype)),"~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus//celltypeSC.txt",quote = F,row.names = F,sep = '\t')

### cytospace -sp expressionSC.txt -ctp celltypeSC.txt -stp expressionST.txt -cp coordinateST.txt -o cytospace_results -sm lap_CSPR



cytospace <- read.csv("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus///cytospace_results/assigned_locations.csv")
cytospace$OriginalCID <- unlist(lapply(strsplit(cytospace$OriginalCID,split = "_"),function(x) paste0(x[-1],collapse =  "_")))
a <- lapply(unique(cytospace$OriginalCID),function(x){
  if(length(unique(cytospace[which(cytospace$OriginalCID%in%x),"row"]))+length(unique(cytospace[which(cytospace$OriginalCID%in%x),"col"]))==2){
    c(unique(cytospace[which(cytospace$OriginalCID%in%x),"row"]),unique(cytospace[which(cytospace$OriginalCID%in%x),"col"]))
  }else{
    c(mean(cytospace[which(cytospace$OriginalCID%in%x),"row"]),mean(cytospace[which(cytospace$OriginalCID%in%x),"col"]))
  }
})

names(a) <- unique(cytospace$OriginalCID)


cyto.mapped <-unique(cytospace$OriginalCID)
cyto.coord <- lapply(cyto.mapped,function(x){
  if(length(unique(cytospace[which(cytospace$OriginalCID%in%x),"row"]))+length(unique(cytospace[which(cytospace$OriginalCID%in%x),"col"]))==2){
    c(unique(cytospace[which(cytospace$OriginalCID%in%x),"row"]),unique(cytospace[which(cytospace$OriginalCID%in%x),"col"]))
  }else{
    c(mean(cytospace[which(cytospace$OriginalCID%in%x),"row"]),mean(cytospace[which(cytospace$OriginalCID%in%x),"col"]))
  }
})
cyto.coord <- matrix(unlist(cyto.coord),ncol = 2,byrow = T)
rownames(cyto.coord) <- cyto.mapped
colnames(cyto.coord) <- c("row","col")
ref.sub.cyto <- subset(ref.sub,cells = cyto.mapped)

set.seed(60611)
rand <- matrix(runif(nrow(cyto.coord)*ncol(cyto.coord))-.5,ncol = 2)*100
cyto.coord <- cyto.coord+rand

ref.sub.cyto[["row"]] <- cyto.coord[,"row"]
ref.sub.cyto[["col"]] <- cyto.coord[,"col"]



dataf<- data.frame(row=ref.sub.cyto[["row"]]$row , col=ref.sub.cyto[["col"]]$col,celltype=ref.sub.cyto$celltype)
dataf$celltype <- factor(dataf$celltype,levels = stringr::str_sort(unique(as.character(dataf$celltype)),numeric = T))

dataf.sub <- dataf[which(dataf$celltype%in%c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells")),]
library(ggplot2)
ggplot(dataf,aes(x=col,y=-row,color=celltype))+geom_point()+theme_classic() 
dataf.sub <- dataf[which(dataf$celltype%in%c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells")),]



tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus/hippo.CA123.cyto.tiff", units="in", width=6, height=6, res=600)
ggplot(dataf.sub,aes(x=col,y=-row,color=celltype))+geom_point()+theme_classic() +scale_color_manual(values = c("#d11141","#ffc425","#00aebd"))+ theme(axis.title.x = element_text(size = 15,face = "bold"),axis.title.y = element_text(size = 15,face = "bold"),axis.text = element_blank())+NoLegend()+xlab("Predicted_X")+ylab("Predicted_Y")
dev.off()
```

```{r}
library(CellTrek)
library(Seurat)


ref.sub <- RenameCells(ref.sub, new.names=make.names(Cells(ref.sub)))
visium <- RenameCells(visium, new.names=make.names(Cells(visium)))
stsc_traint <- CellTrek::traint(st_data=visium, sc_data=ref.sub, sc_assay='SCT', cell_names='celltype',norm = "SCT")

stsc_celltrek <- CellTrek::celltrek(st_sc_int=stsc_traint, int_assay='traint', sc_data=ref.sub, sc_assay = 'SCT', reduction='pca', intp=T, intp_pnt=2000, intp_lin=F, nPCs=30, ntree=1000, dist_thresh=999, top_spot=1, spot_n=100, repel_r=20, repel_iter=20, keep_model=T)$celltrek

stsc_celltrek$celltype <- factor(stsc_celltrek$celltype, levels = sort(unique(as.character(stsc_celltrek$celltype))))


saveRDS(stsc_celltrek,"~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus//stsc_celltrek.rds")

DimPlot(stsc_celltrek,reduction = "celltrek",group.by = "celltype")+ggplot2::ggtitle("")

stsc_celltrek.sub <- subset(stsc_celltrek,cells = which(stsc_celltrek$celltype%in%c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells")))

DimPlot(stsc_celltrek.sub,reduction = "celltrek",group.by = "celltype",cols = c("#d11141","#ffc425","#00aebd"))+ggplot2::ggtitle("")
celltrek.df <- as.data.frame(stsc_celltrek.sub@reductions$celltrek@cell.embeddings)
celltrek.df$celltype <- stsc_celltrek.sub$celltype


tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus/hippo.CA123.celltrek.tiff", units="in", width=6, height=6, res=600)
ggplot(celltrek.df,aes(x=celltrek_1,y=celltrek_2,color=celltype))+geom_point()+theme_classic() +scale_color_manual(values = c("#d11141","#ffc425","#00aebd"))+ theme(axis.title.x = element_text(size = 15,face = "bold"),axis.title.y = element_text(size = 15,face = "bold"),axis.text = element_blank())+NoLegend()+xlab("Predicted_X")+ylab("Predicted_Y")
dev.off()
```




```{r}
anchors <- FindTransferAnchors(reference = visium, query = ref.sub, normalization.method = "SCT")
predictions.assay <- TransferData(anchorset = anchors, refdata = t(visium@images[[1]]@coordinates[,c("imagecol","imagerow")]),dims = 1:30 )

ref.sub[["predicted.row"]]<-as.vector(predictions.assay[2,])

ref.sub[["predicted.col"]]<-as.vector(predictions.assay[1,])

dataf<- data.frame(row=ref.sub[["predicted.row"]]$predicted.row, col=ref.sub[["predicted.col"]]$predicted.col,celltype=ref.sub$celltype)
dataf$celltype <- factor(dataf$celltype,levels = stringr::str_sort(unique(as.character(dataf$celltype)),numeric = T))
library(ggplot2)

ggplot(dataf,aes(x=col,y=-row,color=celltype))+geom_jitter()+theme_classic() +
  xlim(6000, 20000)+
  ylim(-24000, -8000)
dataf.sub <- dataf[which(dataf$celltype%in%c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells")),]

tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus/hippo.CA123.seurat.tiff", units="in", width=6, height=6, res=600)
ggplot(dataf.sub,aes(x=col,y=-row,color=celltype))+geom_point()+theme_classic() +
  scale_color_manual(values = c("#d11141","#ffc425","#00aebd"))+ theme(axis.title.x = element_text(size = 15,face = "bold"),axis.title.y = element_text(size = 15,face = "bold"),axis.text = element_blank())+NoLegend()+xlab("Predicted_X")+ylab("Predicted_Y")
dev.off()

```
```{r}
Tangram.rslt <- read.csv("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus//Tangram.rslt.txt", header=FALSE)
Tangram.rslt <- as.matrix(Tangram.rslt)

set.seed(60611)
rand <- matrix(runif(8000*2)-.5,ncol = 2)*100


tangram.pre <- visium@images$slice1@coordinates[apply(Tangram.rslt,1,which.max),c("imagerow","imagecol")]+rand
ref.sub[["tangram.pre.x"]] <- tangram.pre[,1]
ref.sub[["tangram.pre.y"]] <- tangram.pre[,2]
ref.sub[["tangram.conf"]] <- apply(Tangram.rslt,1,max)


dataf<- data.frame(row=ref.sub[["tangram.pre.x"]]$tangram.pre.x, col=ref.sub[["tangram.pre.y"]]$tangram.pre.y,celltype=ref.sub$celltype,prob=ref.sub$tangram.conf)
dataf$celltype <- factor(dataf$celltype,levels = stringr::str_sort(unique(as.character(dataf$celltype)),numeric = T))
library(ggplot2)
ggplot(dataf,aes(x=col,y=-row,color=celltype))+geom_point()+theme_classic() 

ggplot(dataf,aes(x=col,y=-row,color=prob))+geom_point()+theme_classic() +viridis::scale_color_viridis()

dataf.sub <- dataf
dataf.sub <- dataf.sub[which(dataf.sub$celltype%in%c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells")),]

#dataf.sub <-dataf.sub[intersect(which(dataf.sub$celltype%in%c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells")),which(apply(Tangram.rslt,1,max)>.1)),]
tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus/hippo.CA123.tangram.tiff", units="in", width=6, height=6, res=600)
ggplot(dataf.sub,aes(x=col,y=-row,color=celltype))+geom_point()+theme_classic() +scale_color_manual(values = c("#d11141","#ffc425","#00aebd"))+
  scale_color_manual(values = c("#d11141","#ffc425","#00aebd"))+ theme(axis.title.x = element_text(size = 15,face = "bold"),axis.title.y = element_text(size = 15,face = "bold"),axis.text = element_blank())+NoLegend()+xlab("Predicted_X")+ylab("Predicted_Y")
dev.off()
```


```{r}
scHolo <- as.matrix(dist(hippo.brain.obj.visium$scHolography.sc@meta.data[,c("z3d_sp","y3d_sp","x3d_sp")]))
celltrek <- as.matrix(dist(stsc_celltrek@reductions$celltrek@cell.embeddings))
cyto <- as.matrix(dist(ref.sub.cyto@meta.data[,c("row","col")]))
seurat <- as.matrix(dist(ref.sub@meta.data[,c("predicted.row","predicted.col")]))
tangram <- as.matrix(dist(ref.sub@meta.data[,c("tangram.pre.x","tangram.pre.y")]))
```





```{r}

findClusterDistance <- function(dist.mat, query.cluster,reference.cluster){
  out <- lapply(query.cluster, function(x){
    type <- colnames(ref.sub)[which(ref.sub$celltype %in% x)]
    base <- colnames(ref.sub)[which(ref.sub$celltype %in% reference.cluster)]
    dist.mat[intersect(type,colnames(dist.mat)),intersect(base,colnames(dist.mat))]
  })
  names(out) <- query.cluster
  out
}


scholo.dist <- findClusterDistance(scHolo,query.cluster = c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells"),reference.cluster=c("CA3 Principal cells"))
#lapply(scholo.dist, function(x) summary(rowMeans(x)))

celltrek.dist <- findClusterDistance(celltrek,query.cluster = c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells"),reference.cluster=c("CA3 Principal cells"))
#lapply(celltrek.dist, function(x) summary(rowMeans(x)))


cyto.dist <- findClusterDistance(cyto,query.cluster = c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells"),reference.cluster=c("CA3 Principal cells"))
#lapply(cyto.dist, function(x) summary(rowMeans(x)))


seurat.dist <- findClusterDistance(seurat,query.cluster = c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells"),reference.cluster=c("CA3 Principal cells"))
#lapply(seurat.dist, function(x) summary(rowMeans(x)))

tangram.dist <- findClusterDistance(tangram,query.cluster = c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells"),reference.cluster=c("CA3 Principal cells"))


```


```{r}


scholo.dat <- data.frame(dist = unlist(lapply(scholo.dist, rowMeans)),celltype = ref.sub$celltype[unlist(lapply(names(unlist(lapply(scholo.dist, rowMeans))),function(x) unlist(strsplit(x,split = "[.]"))[-1]))])

celltrek.dat <- data.frame(dist = unlist(lapply(celltrek.dist, rowMeans)),celltype = ref.sub$celltype[unlist(lapply(names(unlist(lapply(celltrek.dist, rowMeans))),function(x) unlist(strsplit(x,split = "[.]"))[-1]))])

cyto.dat <- data.frame(dist = unlist(lapply(cyto.dist, rowMeans)),celltype = ref.sub$celltype[unlist(lapply(names(unlist(lapply(cyto.dist, rowMeans))),function(x) unlist(strsplit(x,split = "[.]"))[-1]))])

seurat.dat <- data.frame(dist = unlist(lapply(seurat.dist, rowMeans)),celltype = ref.sub$celltype[unlist(lapply(names(unlist(lapply(seurat.dist, rowMeans))),function(x) unlist(strsplit(x,split = "[.]"))[-1]))])

tangram.dat <- data.frame(dist = unlist(lapply(tangram.dist, rowMeans)),celltype = ref.sub$celltype[unlist(lapply(names(unlist(lapply(tangram.dist, rowMeans))),function(x) unlist(strsplit(x,split = "[.]"))[-1]))])
```

```{r}
scholo.dat$celltype <- factor(as.character(scholo.dat$celltype),levels = stringr::str_sort(unique(as.character(scholo.dat$celltype)),numeric = T))
celltrek.dat$celltype <- factor(as.character(celltrek.dat$celltype),levels = stringr::str_sort(unique(as.character(celltrek.dat$celltype)),numeric = T))
cyto.dat$celltype <- factor(as.character(cyto.dat$celltype),levels = stringr::str_sort(unique(as.character(cyto.dat$celltype)),numeric = T))
seurat.dat$celltype <- factor(as.character(seurat.dat$celltype),levels = stringr::str_sort(unique(as.character(seurat.dat$celltype)),numeric = T))
tangram.dat$celltype <- factor(as.character(tangram.dat$celltype),levels = stringr::str_sort(unique(as.character(tangram.dat$celltype)),numeric = T))
```


```{r}
library(ggpubr)
library(Seurat)
my_comparisons <- list( c("CA1 Principal cells","CA2 Principal cells"), c("CA2 Principal cells","CA3 Principal cells"))



tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_3rdDraft/CAs.Dist.scholo.tiff", units="in", width=4.5, height=6, res=300)
ggplot(scholo.dat, aes(x=celltype, y=dist/mean(scholo.dat[which(scholo.dat$celltype=="CA3 Principal cells"),"dist"]), fill=celltype)) +
  geom_boxplot()+theme_classic()+scale_fill_manual(values = c("#d11141","#ffc425","#00aebd"))+ 
  geom_signif(comparisons = my_comparisons,test.args = list(size=5),map_signif_level = TRUE)+ theme(axis.title.x = element_blank(),axis.title.y = element_blank(),axis.text = element_text(size = 15,face = "bold"))+NoLegend()+
  scale_x_discrete(labels=c("CA1","CA2","CA3"))
dev.off()


tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_3rdDraft/CAs.Dist.celltrek.tiff", units="in", width=4.5, height=6, res=300)
ggplot(celltrek.dat, aes(x=celltype, y=dist/mean(celltrek.dat[which(celltrek.dat$celltype=="CA3 Principal cells"),"dist"]), fill=celltype)) +
  geom_boxplot()+theme_classic()+scale_fill_manual(values = c("#d11141","#ffc425","#00aebd"))+ 
  geom_signif(comparisons = my_comparisons,test.args = list(size=5),map_signif_level = TRUE)+ theme(axis.title.x = element_blank(),axis.title.y = element_blank(),axis.text = element_text(size = 15,face = "bold"))+NoLegend()+
  scale_x_discrete(labels=c("CA1","CA2","CA3"))
dev.off()


tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_3rdDraft/CAs.Dist.cyto.tiff", units="in", width=4.5, height=6, res=300)
ggplot(cyto.dat, aes(x=celltype, y=dist/mean(cyto.dat[which(cyto.dat$celltype=="CA3 Principal cells"),"dist"]), fill=celltype)) +
  geom_boxplot()+theme_classic()+scale_fill_manual(values = c("#d11141","#ffc425","#00aebd"))+ 
  geom_signif(comparisons = my_comparisons,test.args = list(size=5),map_signif_level = TRUE)+ theme(axis.title.x = element_blank(),axis.title.y = element_blank(),axis.text = element_text(size = 15,face = "bold"))+NoLegend()+
  scale_x_discrete(labels=c("CA1","CA2","CA3"))
dev.off()


tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_3rdDraft/CAs.Dist.seurat.tiff", units="in", width=4.5, height=6, res=300)
ggplot(seurat.dat, aes(x=celltype, y=dist/mean(seurat.dat[which(seurat.dat$celltype=="CA3 Principal cells"),"dist"]), fill=celltype)) +
  geom_boxplot()+theme_classic()+scale_fill_manual(values = c("#d11141","#ffc425","#00aebd"))+ 
  geom_signif(comparisons = my_comparisons,test.args = list(size=5),map_signif_level = TRUE)+ theme(axis.title.x = element_blank(),axis.title.y = element_blank(),axis.text = element_text(size = 15,face = "bold"))+NoLegend()+
  scale_x_discrete(labels=c("CA1","CA2","CA3"))
dev.off()


tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_3rdDraft/CAs.Dist.tangram.tiff", units="in", width=4.5, height=6, res=300)
ggplot(tangram.dat, aes(x=celltype, y=dist/mean(tangram.dat[which(tangram.dat$celltype=="CA3 Principal cells"),"dist"]), fill=celltype)) +
  geom_boxplot()+theme_classic()+scale_fill_manual(values = c("#d11141","#ffc425","#00aebd"))+ 
  geom_signif(comparisons = my_comparisons,test.args = list(size=5),map_signif_level = TRUE)+ theme(axis.title.x = element_blank(),axis.title.y = element_blank(),axis.text = element_text(size = 15,face = "bold"))+NoLegend()+
  scale_x_discrete(labels=c("CA1","CA2","CA3"))
dev.off()
```






