---
title: "R Notebook"
output: html_notebook
---


```{r}

visium.obj  <- readRDS("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus/simulate_vizgen/hippo.vizgen.visium.rds")
slide.seq.obj <- readRDS("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus/simulate_vizgen//slide.seq.ref.scHolo.sim.obj.rds")
xenium.obj <- readRDS("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus/simulate_vizgen//xenium.hippo.ref.scHolo.sim.obj.rds")
merfish.obj <- readRDS("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus/simulate_vizgen//merfish.ref.scHolo.sim.obj.rds")

visium <- as.matrix(dist(visium.obj$scHolography.sc@meta.data[,c("z3d_sp","y3d_sp","x3d_sp")]))

slide.seq <- as.matrix(dist(slide.seq.obj$scHolography.sc@meta.data[,c("z3d_sp","y3d_sp","x3d_sp")]))

xenium <- as.matrix(dist(xenium.obj$scHolography.sc@meta.data[,c("z3d_sp","y3d_sp","x3d_sp")]))
merfish <- as.matrix(dist(merfish.obj$scHolography.sc@meta.data[,c("z3d_sp","y3d_sp","x3d_sp")]))

vizgen.hippo <- readRDS("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus/simulate_vizgen/vizgen.hippo.rds")


real <- as.matrix(dist(GetTissueCoordinates(vizgen.hippo,image = "s2r1")[,c("x","y")]))
colnames(real) <- colnames(vizgen.hippo)
rownames(real) <- colnames(vizgen.hippo)
```

```{r}
library(dplyr)


findKL<-function(realmat,mat){
  realmat.sub <- realmat[rownames(mat),colnames(mat)]
  
  out <- lapply(rownames(mat),function(nam){
    eps <- 1e-20
    X_ <- cbind(realmat.sub[nam,],mat[nam,])
    X_[X_ < eps] <- eps
    X_ <- scale(X_, center = F, scale = colSums(X_)) %>% data.frame
    KL_D <- suppressMessages(philentropy::KL(t(X_), unit = "log"))
    KL_D
  })
  out <- unlist(out)
  names(out) <- rownames(mat)
  out
}

visium.kl<-findKL(realmat =real ,mat = visium)

slide.seq.kl<-findKL(realmat =real ,mat = slide.seq)

xenium.kl<-findKL(realmat = real,mat = xenium)

merfish.kl<-findKL(realmat = real,mat = merfish)

```


```{r}
library(ggpubr)
kl <- c(visium.kl,slide.seq.kl,xenium.kl,merfish.kl)
num.neighbor <- rep(seq(3,15,by=3),5)
method<-c(rep("Visium",length(visium.kl)),rep("Slide.seq",length(slide.seq.kl)),rep("Xenium",length(xenium.kl)),rep("Merfish",length(merfish.kl)))
df <- data.frame(kl=kl, method=factor(method,levels = (c("Visium","Slide.seq","Xenium","Merfish"))))


my_comparisons <- list( c("Visium","Slide.seq"),c("Visium","Xenium"),c("Visium","Merfish"))

tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus/KL_Divergence_ref.tiff", units="in", width=5, height=6, res=600)
ggplot(df, aes(x=method, y=kl, fill=method)) +
  geom_boxplot()+theme_classic()+ 
  geom_signif(comparisons = my_comparisons,map_signif_level = TRUE,y_position = c(.4,.45,.5))+ theme(axis.title.x = element_blank(),axis.text.x = element_text(angle = 45,hjust=1),axis.title.y = element_text(size = 16,face = "bold"),axis.text = element_text(size = 15,face = "bold"))+NoLegend()+ylim(c(0,.57))+scale_fill_brewer(palette = "Set2")+ylab("K-L Divergence")
dev.off()
```

```{r}

neighbor.eval2 <- function(dist.mat,max.neighbor,n.by,start){
  bench <-real
  expr <- vizgen.hippo@assays$Vizgen@counts
  test <- dist.mat
  diag(bench)<-10^15
  diag(test)<-10^15
  
  neighbor.comp.corr.mtx <- c()
  for (i in seq(start+1,(max.neighbor+1),by=n.by)) {
    nn.real.ls <- lapply(colnames(dist.mat), function(x) {
      ind <- which(bench[x,colnames(dist.mat)]<=sort(bench[x,colnames(dist.mat)])[i])
      rowSums(expr[,colnames(dist.mat[,ind])])
    })
    
    nn.ls <- lapply(colnames(dist.mat), function(x) {
      ind <- which(test[x,colnames(dist.mat)]<=sort(test[x,colnames(dist.mat)])[i])
      rowSums(expr[,colnames(dist.mat[,ind])])
    })
    
    neighbor.comp.corr <- unlist(lapply(1:length(nn.ls), function(x) {
      lsa::cosine(nn.real.ls[[x]],nn.ls[[x]])
    }))
    neighbor.comp.corr.mtx <- c(neighbor.comp.corr.mtx,neighbor.comp.corr)
    
  }
  
  neighbor.comp.corr.mtx <- matrix(neighbor.comp.corr.mtx,ncol = max.neighbor/n.by)
  (neighbor.comp.corr.mtx)
}



a.3 <- neighbor.eval2(visium,15,3,3)
b.3 <- neighbor.eval2(slide.seq,15,3,3)
c.3 <- neighbor.eval2(xenium,15,3,3)
d.3 <- neighbor.eval2(merfish,15,3,3)


```

```{r}
cor.mean <- c(colMeans(a.3),colMeans(b.3),colMeans(c.3),colMeans(d.3))
num.neighbor <- rep(seq(3,15,by=3),4)
method<-c(rep("Visium",5),rep("Slide.seq",5),rep("Xenium",5),rep("Merfish",5))
df <- data.frame(mean=cor.mean, method=factor(method,levels = rev(c("Visium","Slide.seq","Xenium","Merfish"))),num.neighbor=factor(num.neighbor,levels = stringr::str_sort(unique(num.neighbor),numeric = T)))


library(viridis)


tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus/hippo.benchmark.cosine.reference.heat.tiff", units="in", width=10, height=6, res=600)
ggplot(df, aes(num.neighbor, method, fill= mean)) + 
  geom_tile() +
  scale_fill_viridis(discrete=FALSE)+theme_classic()+theme(axis.text = element_text(size = 15,face = "bold"),axis.text.x = element_text(angle = 45,hjust=1),axis.title=element_text(size = 18,face = "bold"),legend.title =element_text(size = 13,face = "bold"),legend.text =element_text(size = 12,face = "bold"))+xlab("Size of Neighborhood")+ylab("Reference Tech")+ labs(fill="Mean of Cosine Similarity")+geom_text(aes(label = round(mean, 3)),size=6)
dev.off()
```




```{r}
visium.obj.2  <- readRDS("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus/scHolography.obj.rds")
slide.seq.obj.2 <- readRDS("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus/slide.seq.ref.scHolo.obj.rds")
xenium.obj.2 <- readRDS("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus/xenium.hippo.ref.scHolo.obj.rds")
merfish.obj.2 <- readRDS("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus/merfish.ref.scHolo.obj.rds")

```
```{r}
library(scHolography)
scHolographyPlot(visium.obj.2,color.by = "celltype",cells = which(visium.obj.2$scHolography.sc$celltype%in%c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells")),color = c(c("black",c("#d11141","#ffc425","#00aebd")),rep("black",15)))


fig1 <- scHolographyPlot(slide.seq.obj.2,color.by = "celltype",cells = which(slide.seq.obj.2$scHolography.sc$celltype%in%c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells")),color = c(c("black",c("#d11141","#ffc425","#00aebd")),rep("black",15)))%>% plotly::layout(scene = list(camera = list(eye = list(x = 2.25, z = 0, y = 0))))
plotly::orca(fig1, "hippo.CA123.slide.svg",width = 4.5,height = 6)

fig1 <- scHolographyPlot(xenium.obj.2,color.by = "celltype",cells = which(xenium.obj.2$scHolography.sc$celltype%in%c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells")),color = c(c("black",c("#d11141","#ffc425","#00aebd")),rep("black",15)))%>% plotly::layout(scene = list(camera = list(eye = list(x = 0, z = 2, y = 0))))

plotly::orca(fig1, "hippo.CA123.xenium.svg",width = 4.5,height = 6)



fig1 <- scHolographyPlot(merfish.obj.2,color.by = "celltype",cells = which(merfish.obj.2$scHolography.sc$celltype%in%c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells")),color = c(c("black",c("#d11141","#ffc425","#00aebd")),rep("black",15)))%>% plotly::layout(scene = list(camera = list(eye = list(x = 2, z = 0, y = 0))))
fig1
plotly::orca(fig1, "hippo.CA123.merfish.svg",width = 4.5,height = 6)
```



```{r}
ref <- readRDS("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/Mouse Hippocampus//mouse_hippocampus_reference.rds")
set.seed(60611)
ref.sub <- subset(ref, cells = sample(colnames(ref),8000))


findClusterDistance <- function(dist.mat, query.cluster,reference.cluster){
  out <- lapply(query.cluster, function(x){
    type <- colnames(ref.sub)[which(ref.sub$celltype %in% x)]
    base <- colnames(ref.sub)[which(ref.sub$celltype %in% reference.cluster)]
    dist.mat[intersect(type,colnames(dist.mat)),intersect(base,colnames(dist.mat))]
  })
  names(out) <- query.cluster
  out
}



eval.plot <-function(scHolography.obj){
  
  scHolo <- as.matrix(dist(scHolography.obj$scHolography.sc@meta.data[,c("z3d_sp","y3d_sp","x3d_sp")]))
  library(scHolography)
  scholo.dist <- findClusterDistance(scHolo,query.cluster = c("CA1 Principal cells","CA2 Principal cells","CA3 Principal cells"),reference.cluster=c("CA3 Principal cells"))
  
  scholo.dat <- data.frame(dist = unlist(lapply(scholo.dist, rowMeans)),celltype = ref.sub$celltype[unlist(lapply(names(unlist(lapply(scholo.dist, rowMeans))),function(x) unlist(strsplit(x,split = "[.]"))[-1]))])
  
  scholo.dat$celltype <- factor(as.character(scholo.dat$celltype),levels = stringr::str_sort(unique(as.character(scholo.dat$celltype)),numeric = T))
  
  library(ggpubr)
  my_comparisons <- list( c("CA1 Principal cells","CA2 Principal cells"), c("CA2 Principal cells","CA3 Principal cells"))
  
  ggplot(scholo.dat, aes(x=celltype, y=dist/mean(scholo.dat[which(scholo.dat$celltype=="CA3 Principal cells"),"dist"]), fill=celltype)) +
    geom_boxplot()+theme_classic()+scale_fill_manual(values = c("#d11141","#ffc425","#00aebd"))+ 
  geom_signif(comparisons = my_comparisons,test.args = list(size=5),map_signif_level = TRUE)+ theme(axis.title.x = element_blank(),axis.title.y = element_blank(),axis.text = element_text(size = 15,face = "bold"))+NoLegend()+
  scale_x_discrete(labels=c("CA1","CA2","CA3"))}


```

```{r}
eval.plot(visium.obj.2)

tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_3rdDraft//CAs.Dist.slide.seq.tiff", units="in", width=4.5, height=6, res=300)
eval.plot(slide.seq.obj.2)
dev.off()

tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_3rdDraft//CAs.Dist.xenium.tiff", units="in", width=4.5, height=6, res=300)
eval.plot(xenium.obj.2)
dev.off()

tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_3rdDraft//CAs.Dist.merfish.tiff", units="in", width=4.5, height=6, res=300)
eval.plot(merfish.obj.2)
dev.off()

```



