---
title: "R Notebook"
output: html_notebook
---

```{r}

#####Load in data & infer centroid
library(zellkonverter)
library(Seurat)
library(terra)
library(ggplot2)
counts_h5ad <- readH5AD("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/3D Merfish/Merfish new/data/counts.h5ad")
counts.mat <- counts_h5ad@assays@data$X
merfish.meta <- read.csv("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/3D Merfish/Merfish new/data/cell_labels.csv")
merfish.meta$X <- paste0("cell_",(merfish.meta$X))
colnames(counts.mat) <- paste0("cell_",as.numeric(colnames(counts.mat)))
rownames(merfish.meta) <- merfish.meta$X

counts.mat.sub <- counts.mat[,rownames(merfish.meta)]

merfish.seurat <- CreateSeuratObject(counts = counts.mat.sub,assay = "RNA",meta.data = merfish.meta)

merfish.seurat <- SCTransform(merfish.seurat)
merfish.seurat <- RunPCA(merfish.seurat)
merfish.seurat <- FindNeighbors(merfish.seurat)
merfish.seurat <- FindClusters(merfish.seurat)
merfish.seurat <- RunUMAP(merfish.seurat,dims = 1:30)

mouse1sample1.boundary <- read.csv("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/3D Merfish/Merfish new/data/segmented_cells_mouse1sample1.csv")

mouse1sample1.boundary$X <- paste0("cell_",(mouse1sample1.boundary$X))
rownames(mouse1sample1.boundary) <- mouse1sample1.boundary$X


as.numeric(unlist(strsplit(mouse1sample1.boundary$boundaryX_z3[1],",")))
as.numeric(unlist(strsplit(mouse1sample1.boundary$boundaryY_z3[1],",")))

mouse1sample1.boundary.cent <- matrix(nrow=nrow(mouse1sample1.boundary), ncol = 2)
for (i in 1:nrow(mouse1sample1.boundary)) {
  if(length(unlist(strsplit(mouse1sample1.boundary$boundaryX_z3[i],",")))<3){
    mouse1sample1.boundary.cent[i, ]<- c(NA,NA)
  }else{
    mouse1sample1.boundary.cent[i, ]<- unlist(centroids(vect(cbind(
      as.numeric(unlist(strsplit(mouse1sample1.boundary$boundaryX_z3[i],","))),
      as.numeric(unlist(strsplit(mouse1sample1.boundary$boundaryY_z3[i],",")))),
      type="polygons"),inside=T)@ptr$coordinates())
  }
  
}

rownames(mouse1sample1.boundary.cent) <- rownames(mouse1sample1.boundary)
colnames(mouse1sample1.boundary.cent) <-c("CentroidX","CentroidY")
mouse1sample1.boundary.cent <- as.data.frame(mouse1sample1.boundary.cent)
merfish.seurat.mouse1_sample1 <- subset(merfish.seurat,cells=which(merfish.seurat$sample_id%in%"mouse1_sample1"))

merfish.seurat.mouse1_sample1 <- AddMetaData(merfish.seurat.mouse1_sample1,mouse1sample1.boundary.cent)

merfish.seurat.mouse1_sample1.slice31 <- subset(merfish.seurat.mouse1_sample1,cells=which(merfish.seurat.mouse1_sample1$slice_id%in%"mouse1_slice31"))
merfish.seurat.mouse1_sample1.slice40 <- subset(merfish.seurat.mouse1_sample1,cells=which(merfish.seurat.mouse1_sample1$slice_id%in%"mouse1_slice40"))
merfish.seurat.mouse1_sample1.slice50 <- subset(merfish.seurat.mouse1_sample1,cells=which(merfish.seurat.mouse1_sample1$slice_id%in%"mouse1_slice50"))


merfish.seurat.mouse1_sample1.slice31@meta.data$CentroidX <- -merfish.seurat.mouse1_sample1.slice31@meta.data$CentroidX
merfish.seurat.mouse1_sample1.slice31@meta.data$CentroidY <- -merfish.seurat.mouse1_sample1.slice31@meta.data$CentroidY
merfish.seurat.mouse1_sample1.slice40@meta.data$CentroidX <- -merfish.seurat.mouse1_sample1.slice40@meta.data$CentroidX
merfish.seurat.mouse1_sample1.slice40@meta.data$CentroidY <- -merfish.seurat.mouse1_sample1.slice40@meta.data$CentroidY
merfish.seurat.mouse1_sample1.slice50@meta.data$CentroidY <- -merfish.seurat.mouse1_sample1.slice50@meta.data$CentroidY

ggplot(merfish.seurat.mouse1_sample1.slice31@meta.data,aes(x=CentroidX,y=CentroidY,color=subclass))+
  geom_point()+theme_classic()
ggplot(merfish.seurat.mouse1_sample1.slice40@meta.data,aes(x=CentroidX,y=CentroidY,color=subclass))+
  geom_point()+theme_classic()
ggplot(merfish.seurat.mouse1_sample1.slice50@meta.data,aes(x=CentroidX,y=CentroidY,color=subclass))+
  geom_point()+theme_classic()

```

```{r}
### ### Create Seurat objects, Keep only cells with inferred centroids, focus on slice 31, 40, & 50, adjust three slice position using slice 40 as the reference

merfish.seurat.mouse1_sample1.slice31.sub <-subset(merfish.seurat.mouse1_sample1.slice31,cells=which(is.na(merfish.seurat.mouse1_sample1.slice31$CentroidX)==F))
merfish.seurat.mouse1_sample1.slice40.sub <-subset(merfish.seurat.mouse1_sample1.slice40,cells=which(is.na(merfish.seurat.mouse1_sample1.slice40$CentroidX)==F))
merfish.seurat.mouse1_sample1.slice50.sub <-subset(merfish.seurat.mouse1_sample1.slice50,cells=which(is.na(merfish.seurat.mouse1_sample1.slice50$CentroidX)==F))


c(median(merfish.seurat.mouse1_sample1.slice31.sub@meta.data$CentroidX ),median(merfish.seurat.mouse1_sample1.slice31.sub@meta.data$CentroidY))
c(median(merfish.seurat.mouse1_sample1.slice40.sub@meta.data$CentroidX),median(merfish.seurat.mouse1_sample1.slice40.sub@meta.data$CentroidY))
c(median(merfish.seurat.mouse1_sample1.slice50.sub@meta.data$CentroidX),median(merfish.seurat.mouse1_sample1.slice50.sub@meta.data$CentroidY))


merfish.seurat.mouse1_sample1.slice31.sub@meta.data[,c("CentroidX","CentroidY")] <- t(t(merfish.seurat.mouse1_sample1.slice31.sub@meta.data[,c("CentroidX","CentroidY")])-c(median(merfish.seurat.mouse1_sample1.slice31.sub@meta.data$CentroidX ),median(merfish.seurat.mouse1_sample1.slice31.sub@meta.data$CentroidY))+c(median(merfish.seurat.mouse1_sample1.slice40.sub@meta.data$CentroidX),median(merfish.seurat.mouse1_sample1.slice40.sub@meta.data$CentroidY)))
merfish.seurat.mouse1_sample1.slice50.sub@meta.data[,c("CentroidX","CentroidY")] <- t(t(merfish.seurat.mouse1_sample1.slice50.sub@meta.data[,c("CentroidX","CentroidY")])-c(median(merfish.seurat.mouse1_sample1.slice50.sub@meta.data$CentroidX ),median(merfish.seurat.mouse1_sample1.slice50.sub@meta.data$CentroidY))+c(median(merfish.seurat.mouse1_sample1.slice40.sub@meta.data$CentroidX),median(merfish.seurat.mouse1_sample1.slice40.sub@meta.data$CentroidY)))

merfish.seurat.mouse1_sample1.30.40.50sub <- subset(merfish.seurat.mouse1_sample1, cells=c(colnames(merfish.seurat.mouse1_sample1.slice31.sub),colnames(merfish.seurat.mouse1_sample1.slice40.sub),colnames(merfish.seurat.mouse1_sample1.slice50.sub)))
merfish.seurat.mouse1_sample1.30.40.50sub <- AddMetaData(merfish.seurat.mouse1_sample1.30.40.50sub, metadata = rbind(merfish.seurat.mouse1_sample1.slice31.sub@meta.data[,c("CentroidX","CentroidY")] ,merfish.seurat.mouse1_sample1.slice40.sub@meta.data[,c("CentroidX","CentroidY")] ,merfish.seurat.mouse1_sample1.slice50.sub@meta.data[,c("CentroidX","CentroidY")] )
)  

merfish.seurat.mouse1_sample1.30.40.50sub[["Inferred_Z"]] <- as.numeric(unlist(lapply(merfish.seurat.mouse1_sample1.30.40.50sub$slice_id, function(x) { unlist(strsplit(x,"slice"))[2] })))*10

library(dplyr)
library(plotly)
plot_ly(merfish.seurat.mouse1_sample1.30.40.50sub@meta.data,x=~CentroidX,y=~CentroidY,z=~Inferred_Z,color=~subclass,colors = "Paired", marker = list(size = 2))%>% add_markers()
```
```{r}
library(scatterplot3d)
merfish.seurat.mouse1_sample1.30.40.50sub.sub <- merfish.seurat.mouse1_sample1.30.40.50sub[,which(merfish.seurat.mouse1_sample1.30.40.50sub$class_label%in%"Glutamatergic")]

color <- (RColorBrewer::brewer.pal(12,"Paired"))[1:length(unique(merfish.seurat.mouse1_sample1.30.40.50sub.sub@meta.data$subclass))] 
colors <- color[as.numeric(factor(merfish.seurat.mouse1_sample1.30.40.50sub.sub@meta.data$subclass,levels = stringr::str_sort(unique(merfish.seurat.mouse1_sample1.30.40.50sub.sub@meta.data$subclass),numeric = T)))]

tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/3D Merfish//Merfish.dist.3D.layer.tiff", units="in", width=8, height=6, res=600)
scatterplot3d(merfish.seurat.mouse1_sample1.30.40.50sub.sub@meta.data$CentroidX,-merfish.seurat.mouse1_sample1.30.40.50sub.sub@meta.data$CentroidY,merfish.seurat.mouse1_sample1.30.40.50sub.sub@meta.data$Inferred_Z, pch = 16, grid=T, box=FALSE,color=colors, angle = 70,xlab = "x",ylab = "y",zlab = "z")
dev.off()
```



```{r}
tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/3D Merfish//Merfish.dist.3D.layer.zlayer.tiff", units="in", width=8, height=6, res=600)
colors<-c("#308695","#d45769","#e69d45")[as.numeric(factor(merfish.seurat.mouse1_sample1.30.40.50sub.sub@meta.data$Inferred_Z))]
scatterplot3d(merfish.seurat.mouse1_sample1.30.40.50sub.sub@meta.data$CentroidX,-merfish.seurat.mouse1_sample1.30.40.50sub.sub@meta.data$CentroidY,merfish.seurat.mouse1_sample1.30.40.50sub.sub@meta.data$Inferred_Z, pch = 16, grid=T, box=FALSE,color=colors, angle = 70,xlab = "x",ylab = "y",zlab = "z")
dev.off()
```

```{r}
### Create an seurat object with spatial info
merfish.seurat.mouse1_sample1.slice40.sub@images$image =  new(
  Class = 'SlideSeq',
  assay = "Spatial",
  key = "image_",
  coordinates = merfish.seurat.mouse1_sample1.slice40.sub@meta.data[,c("CentroidX","CentroidY")]
)
```

```{r}
### scHolography Inference (Slice40 Reference on Slice40 Query)
library(scHolography)
sp.integrated.merfish.slice40toslice40 <- dataAlign(low.res.sp =  merfish.seurat.mouse1_sample1.slice40.sub,high.res.sp =  merfish.seurat.mouse1_sample1.slice40.sub,scProcessed = T,stProcessed = T,future.size = 7000)
scHolography.obj.slice40toslice40<- trainHolography(sp.integrated.merfish.slice40toslice40)
saveRDS(scHolography.obj.slice40toslice40,"~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/3D Merfish/Merfish new/merfish.slice40toslice40.rds")
scHolographyPlot(scHolography.obj.slice40toslice40,color.by = "subclass")


def.col <- rep("black",length(unique(scHolography.obj.slice40toslice40$scHolography.sc$subclass)))
def.col[which(stringr::str_sort(unique(scHolography.obj.slice40toslice40$scHolography.sc$subclass),numeric = T)%in%stringr::str_sort(unique(scHolography.obj.slice40toslice40$scHolography.sc$subclass[which(scHolography.obj.slice40toslice40$scHolography.sc$class_label%in%"Glutamatergic")]),numeric = T))] <-(RColorBrewer::brewer.pal(12,"Paired"))[1:9] 




fig.2dq <- scHolographyPlot(scHolography.obj.slice40toslice40,color.by = "subclass",cells =which(scHolography.obj.slice40toslice40$scHolography.sc$class_label%in%"Glutamatergic") ,color = def.col)%>% plotly::layout(scene = list(camera = list(eye = list(x = 2.25, z = 0, y = 0))))
plotly::orca(fig.2dq, "fig.2dq.svg",width = 4.5,height = 6)

fig.2dq
```

```{r}
merfish.seurat.mouse1_sample1.slice40.sub.glu.sub <- merfish.seurat.mouse1_sample1.slice40.sub[,which(merfish.seurat.mouse1_sample1.slice40.sub$class_label%in%"Glutamatergic")]

slice40 <-plot_ly(merfish.seurat.mouse1_sample1.slice40.sub.glu.sub@meta.data,x=~CentroidX,y=~-CentroidY,color=~subclass,colors = "Paired", marker = list(size = 3))%>% add_markers()
plotly::orca(slice40, "slice40.svg",width = 4.5,height = 6)

tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/3D Merfish//slice40.tiff", units="in", width=8, height=7, res=600)
ggplot(merfish.seurat.mouse1_sample1.slice40.sub.glu.sub@meta.data)+
  geom_point(aes(x=CentroidX,y = -CentroidY,color=subclass))+theme_void()+scale_color_brewer(palette = "Paired")+theme(axis.title = element_blank(),axis.text = element_blank(),axis.ticks = element_blank())+Seurat::NoLegend()
dev.off()

slice40
```

```{r}
### scHolography Inference (Slice40 Reference on Slice31&40&50 combined query)
set.seed(60611)
merfish.seurat.mouse1_sample1.30.40.50sub.8000 <- subset(merfish.seurat.mouse1_sample1.30.40.50sub, cells=sample(colnames(merfish.seurat.mouse1_sample1.30.40.50sub),8000))

sp.integrated.merfish.slice3Dtoslice40 <- dataAlign(low.res.sp =  merfish.seurat.mouse1_sample1.slice40.sub,high.res.sp =  merfish.seurat.mouse1_sample1.30.40.50sub.8000,scProcessed = T,stProcessed = T,future.size = 7000)
scHolography.obj.slice3Dtoslice40 <- trainHolography(sp.integrated.merfish.slice3Dtoslice40)
saveRDS(scHolography.obj.slice3Dtoslice40,"~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/3D Merfish/Merfish new//merfish.slice3Dtoslice40.rds")
def.col <- rep("black",length(unique(scHolography.obj.slice3Dtoslice40$scHolography.sc$subclass)))
def.col[which(stringr::str_sort(unique(scHolography.obj.slice3Dtoslice40$scHolography.sc$subclass),numeric = T)%in%stringr::str_sort(unique(scHolography.obj.slice3Dtoslice40$scHolography.sc$subclass[which(scHolography.obj.slice3Dtoslice40$scHolography.sc$class_label%in%"Glutamatergic")]),numeric = T))] <-(RColorBrewer::brewer.pal(12,"Paired"))[1:9] 


fig.3dq <- scHolographyPlot(scHolography.obj.slice3Dtoslice40,color.by = "subclass",cells =which(scHolography.obj.slice3Dtoslice40$scHolography.sc$class_label%in%"Glutamatergic") ,color = def.col)%>% plotly::layout(scene = list(camera = list(eye = list(x = 0, z = 1.75, y = 0))))
fig.3dq


plotly::orca(fig.3dq, "fig.3dq.svg",width = 4.5,height = 6)
```

```{r}
fig.3dq.layer <-scHolographyPlot(scHolography.obj.slice3Dtoslice40,color.by = "Inferred_Z",cells =which(scHolography.obj.slice3Dtoslice40$scHolography.sc$class_label%in%"Glutamatergic"),color = c("#308695","#d45769","#e69d45"))%>% plotly::layout(scene = list(camera = list(eye = list(x = 0, z = 1.75, y = 0))))
plotly::orca(fig.3dq.layer, "fig.3dq.layer.svg",width = 4.5,height = 6)
```

```{r}
  my_comparisons <- list( c("310","400"), c("400","500"))
tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/3D Merfish//Cortex.dist.3D.layer.tiff", units="in", width=5, height=6, res=600)
scHolography::clusterDistanceBoxplot(scHolography.obj.slice3Dtoslice40,annotationToUse = "Inferred_Z",query.cluster.list = c("310","400","500"),reference.cluster = c("310"))+ theme(legend.position = "none")+scale_fill_manual(values = c("#308695","#d45769","#e69d45"))+theme_classic()+ 
  theme(axis.title.x = element_blank(),axis.text.x = element_text(angle = 45,hjust=1),axis.title.y = element_text(size = 16,face = "bold"),axis.text = element_text(size = 15,face = "bold"))+NoLegend()+ylab("SMN Distance to slice 310")+ 
  geom_signif(comparisons = my_comparisons,map_signif_level = TRUE,test.args = list(alternative=("less"),size=5),y_position = c(4.25,4.75,5.25))
dev.off()
```


```{r}
scHolography::clusterDistanceBoxplot(scHolography.obj.slice3Dtoslice40,annotationToUse = "subclass",query.cluster.list = c(
  "L2/3 IT","L4/5 IT","L5 IT","L6 IT","L6 IT Car3","L5 ET","L5/6 NP","L6 CT","L6b"),reference.cluster = c("L6 CT","L6b"))+ theme(legend.position = "none")+scale_fill_manual(values = color[c(1,2,4,7,8,3,5,6,9)])

my_comparisons <- list( c("L2/3 IT","L4/5 IT"),c("L2/3 IT","L5 IT"),c("L2/3 IT","L6 IT"))

tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/3D Merfish//Cortex.dist.3D.tiff", units="in", width=5, height=6, res=600)
scHolography::clusterDistanceBoxplot(scHolography.obj.slice3Dtoslice40,annotationToUse = "subclass",query.cluster.list = c(
  "L2/3 IT","L4/5 IT","L5 IT","L6 IT"),reference.cluster = c("L6 IT","L6 IT Car3","L6 CT","L6b"))+ theme(legend.position = "none")+scale_fill_manual(values = color[c(1,2,4,7,8,3,5,6,9)])+theme_classic()+ 
  theme(axis.title.x = element_blank(),axis.text.x = element_text(angle = 45,hjust=1),axis.title.y = element_text(size = 16,face = "bold"),axis.text = element_text(size = 15,face = "bold"))+NoLegend()+ylab("SMN Distance to L6")+ 
  geom_signif(comparisons = my_comparisons,map_signif_level = TRUE,test.args = list(alternative=("greater"),size=5),y_position = c(6.25,6.75,7.25))


scHolography::clusterDistanceBoxplot(scHolography.obj.slice3Dtoslice40,annotationToUse = "subclass",query.cluster.list = c(
  "L2/3 IT","L4/5 IT","L5 IT","L6 IT"),reference.cluster = c("L6 IT","L6 IT Car3","L6 CT","L6b"))+ theme(legend.position = "none")+scale_fill_manual(values = color[c(1,2,4,7,8,3,5,6,9)])+theme_classic()+ 
  theme(axis.title.x = element_blank(),axis.text.x = element_text(angle = 45,hjust=1),axis.title.y = element_text(size = 16,face = "bold"),axis.text = element_text(size = 15,face = "bold"))+NoLegend()+ylab("SMN Distance to L6")+ 
  geom_signif(comparisons = my_comparisons,map_signif_level = TRUE,test.args = list(alternative=("greater"),size=5),y_position = c(6.25,6.75,7.25))

dev.off()
```
```{r}

scHolography::clusterDistanceBoxplot(scHolography.obj.slice3Dtoslice40,annotationToUse = "label",query.cluster.list = c(sort(unique(scHolography.obj.slice3Dtoslice40$scHolography.sc$label))[c(4:14,21:24,36:39)]),reference.cluster = c( "L6_IT_1","L6_IT_2","L6_IT_3", "L6_IT_Car3" ))

```

```{r}
tiff("~/OneDrive - Northwestern University/Northwestern/Yi Lab/Manuscript/Code_2ndDraft/3D Merfish//Cortex.dist.2D.tiff", units="in", width=5, height=6, res=600)
scHolography::clusterDistanceBoxplot(scHolography.obj.slice40toslice40,annotationToUse = "subclass",query.cluster.list = c(
  "L2/3 IT","L4/5 IT","L5 IT","L6 IT"),reference.cluster = c("L6 IT","L6 IT Car3","L6 CT","L6b"))+ theme(legend.position = "none")+scale_fill_manual(values = color[c(1,2,4,7,8,3,5,6,9)])+theme_classic()+ 
  theme(axis.title.x = element_blank(),axis.text.x = element_text(angle = 45,hjust=1),axis.title.y = element_text(size = 16,face = "bold"),axis.text = element_text(size = 15,face = "bold"))+NoLegend()+ylab("SMN Distance to L6")+ 
  geom_signif(comparisons = my_comparisons,map_signif_level = TRUE,test.args = list(alternative=("greater"),size=5),y_position = c(6,6.5,7))

dev.off()
```