---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Seurat)
library(ggplot2)
library(dplyr)
library(plotly)
library(scatterplot3d)
library(ggpubr)
library(scHolography)
merfish.seurat.mouse1_sample1 <- readRDS("/projects/b1042/YiLab/Cady/Code_3rdDraft/Merfish_3D//merfish.seurat.mouse1_sample1.rds")
```


```{r}
merfish.seurat.mouse1_sample1.slice1.sub <- readRDS("/projects/b1042/YiLab/Cady/Code_3rdDraft/Merfish_3D/paste_sample1/mouse1_slice1_1500sub.rds")
merfish.seurat.mouse1_sample1.slice10.sub <- readRDS("/projects/b1042/YiLab/Cady/Code_3rdDraft/Merfish_3D/paste_sample1/mouse1_slice10_1500sub.rds")
merfish.seurat.mouse1_sample1.slice21.sub <- readRDS("/projects/b1042/YiLab/Cady/Code_3rdDraft/Merfish_3D/paste_sample1/mouse1_slice21_1500sub.rds")
merfish.seurat.mouse1_sample1.slice31.sub <- readRDS("/projects/b1042/YiLab/Cady/Code_3rdDraft/Merfish_3D/paste_sample1/mouse1_slice31_1500sub.rds")
merfish.seurat.mouse1_sample1.slice40.sub <- readRDS("/projects/b1042/YiLab/Cady/Code_3rdDraft/Merfish_3D/paste_sample1/mouse1_slice40_1500sub.rds")
merfish.seurat.mouse1_sample1.slice50.sub <- readRDS("/projects/b1042/YiLab/Cady/Code_3rdDraft/Merfish_3D/paste_sample1/mouse1_slice50_1500sub.rds")


merfish.seurat.mouse1_sample1.sub.comb <- subset(merfish.seurat.mouse1_sample1, cells=c(colnames(merfish.seurat.mouse1_sample1.slice1.sub),colnames(merfish.seurat.mouse1_sample1.slice10.sub),colnames(merfish.seurat.mouse1_sample1.slice21.sub),colnames(merfish.seurat.mouse1_sample1.slice31.sub),colnames(merfish.seurat.mouse1_sample1.slice40.sub),colnames(merfish.seurat.mouse1_sample1.slice50.sub)))


paste.pred <- read.csv("/projects/b1042/YiLab/Cady/Code_3rdDraft/Merfish_3D/paste_sample1/filename.csv")
rownames(paste.pred) <- c(colnames(merfish.seurat.mouse1_sample1.slice1.sub),colnames(merfish.seurat.mouse1_sample1.slice10.sub),colnames(merfish.seurat.mouse1_sample1.slice21.sub),colnames(merfish.seurat.mouse1_sample1.slice31.sub),colnames(merfish.seurat.mouse1_sample1.slice40.sub),colnames(merfish.seurat.mouse1_sample1.slice50.sub))
paste.pred$Inferred_Z <- sort(rep(c(10, 100,210,310,400,500),1500))

merfish.seurat.mouse1_sample1.sub.comb <- AddMetaData(merfish.seurat.mouse1_sample1.sub.comb, metadata = paste.pred[,c("x","y","Inferred_Z")])
 
saveRDS(merfish.seurat.mouse1_sample1.sub.comb,"/projects/b1042/YiLab/Cady/Code_3rdDraft/Merfish_3D/paste_sample1/merfish.seurat.mouse1_sample1.sub.comb.rds")


plot_ly(merfish.seurat.mouse1_sample1.sub.comb@meta.data,x=~x,y=~y,z=~Inferred_Z,color=~subclass,colors = "Paired", marker = list(size = 2))%>% add_markers()
```
```{r}

merfish.seurat.mouse1_sample1.sub.comb.sub <- merfish.seurat.mouse1_sample1.sub.comb[,which(merfish.seurat.mouse1_sample1.sub.comb$class_label%in%"Glutamatergic")]

color <- (RColorBrewer::brewer.pal(12,"Paired"))[1:length(unique(merfish.seurat.mouse1_sample1.sub.comb.sub@meta.data$subclass))] 
colors <- color[as.numeric(factor(merfish.seurat.mouse1_sample1.sub.comb.sub@meta.data$subclass,levels = stringr::str_sort(unique(merfish.seurat.mouse1_sample1.sub.comb.sub@meta.data$subclass),numeric = T)))]

tiff("/projects/b1042/YiLab/Cady/Code_3rdDraft/Merfish_3D/sample1_Merfish.dist.3D.layer.tiff", units="in", width=8, height=6, res=600)
scatterplot3d(merfish.seurat.mouse1_sample1.sub.comb.sub@meta.data$x,merfish.seurat.mouse1_sample1.sub.comb.sub@meta.data$y,merfish.seurat.mouse1_sample1.sub.comb.sub@meta.data$Inferred_Z, pch = 16, grid=T, box=FALSE,color=colors, xlab = "x",ylab = "y",zlab = "z")
dev.off()

tiff("/projects/b1042/YiLab/Cady/Code_3rdDraft/Merfish_3D//sample1_Merfish.dist.3D.layer.zlayer.tiff", units="in", width=8, height=6, res=600)
colors<-c('#e41a1c','#377eb8','#4daf4a','#984ea3','#FF7F00','#FFFF33')[as.numeric(factor(merfish.seurat.mouse1_sample1.sub.comb.sub@meta.data$Inferred_Z))]
scatterplot3d(merfish.seurat.mouse1_sample1.sub.comb.sub@meta.data$x,merfish.seurat.mouse1_sample1.sub.comb.sub@meta.data$y,merfish.seurat.mouse1_sample1.sub.comb.sub@meta.data$Inferred_Z, pch = 16, grid=T, box=FALSE,color=colors, angle = 70,xlab = "x",ylab = "y",zlab = "z")
dev.off()
```


```{r}
### Create an seurat object with spatial info
merfish.seurat.mouse1_sample1.slice50.sub@images$image =  new(
  Class = 'SlideSeq',
  assay = "Spatial",
  key = "image_",
  coordinates = merfish.seurat.mouse1_sample1.slice50.sub@meta.data[,c("CentroidX","CentroidY")]
)
```


### scHolography Inference (slice50 Reference on slice50 Query)
```{r}
merfish.seurat.mouse1_sample1.slice50.sub_dup <- merfish.seurat.mouse1_sample1.slice50.sub
merfish.seurat.mouse1_sample1.slice50.sub_dup <- RenameCells(merfish.seurat.mouse1_sample1.slice50.sub_dup, paste0(colnames(merfish.seurat.mouse1_sample1.slice50.sub_dup),"_dup")) 
```

### scHolography Inference (slice50 Reference on Sample 1 Slices combined query)
```{r}
sp.integrated.merfish.slice3Dtoslice50 <- dataAlign(low.res.sp =  merfish.seurat.mouse1_sample1.slice50.sub_dup,high.res.sp =  merfish.seurat.mouse1_sample1.sub.comb,scProcessed = T,stProcessed = T,future.size = 7000)
scHolography.obj.slice3Dtoslice50 <- trainHolography(sp.integrated.merfish.slice3Dtoslice50)
saveRDS(scHolography.obj.slice3Dtoslice50,"/projects/b1042/YiLab/Cady/Code_3rdDraft/Merfish_3D/paste_sample1//merfish.slice3Dtoslice50.rds")
def.col <- rep("black",length(unique(scHolography.obj.slice3Dtoslice50$scHolography.sc$subclass)))
def.col[which(stringr::str_sort(unique(scHolography.obj.slice3Dtoslice50$scHolography.sc$subclass),numeric = T)%in%stringr::str_sort(unique(scHolography.obj.slice3Dtoslice50$scHolography.sc$subclass[which(scHolography.obj.slice3Dtoslice50$scHolography.sc$class_label%in%"Glutamatergic")]),numeric = T))] <-(RColorBrewer::brewer.pal(12,"Paired"))[1:9] 




fig.3dq <- scHolographyPlot(scHolography.obj.slice3Dtoslice50,color.by = "subclass",cells =which(scHolography.obj.slice3Dtoslice50$scHolography.sc$class_label%in%"Glutamatergic") ,color = def.col)%>% plotly::layout(scene = list(camera = list(eye = list(x = 1.6, z = 0.5, y = 0))))
fig.3dq

plotly::orca(fig.3dq, "sample1_slice50.svg",width = 4.5,height = 6)
```



```{r}

my_comparisons <- list( c("10","100"), c("100","210"), c("210","310"), c("310","400"),c('400','500'),c("10","210"), c("210","400"))
tiff("/projects/b1042/YiLab/Cady/Code_3rdDraft/Merfish_3D//sample1_s50_Cortex.dist.3D.layer.tiff", units="in", width=5, height=6, res=600)
scHolography::clusterDistanceBoxplot(scHolography.obj.slice3Dtoslice50,annotationToUse = "Inferred_Z",query.cluster.list = c("10", "100", "210", "310","400","500"),reference.cluster = c("10"))+ theme(legend.position = "none")+scale_fill_manual(values = c('#e41a1c','#377eb8','#4daf4a','#984ea3','#FF7F00','#FFFF33'))+theme_classic()+ 
  theme(axis.title.x = element_blank(),axis.text.x = element_text(angle = 45,hjust=1),axis.title.y = element_text(size = 16,face = "bold"),axis.text = element_text(size = 15,face = "bold"))+NoLegend()+ylab("SMN Distance to slice 10")+ 
  geom_signif(comparisons = my_comparisons,map_signif_level = TRUE,test.args = list(size=5),y_position = c(rep(5,5),rep(5.5,2)))
dev.off()
```


```{r}
scHolography::clusterDistanceBoxplot(scHolography.obj.slice3Dtoslice50,annotationToUse = "subclass",query.cluster.list = c(
  "L2/3 IT","L4/5 IT","L5 IT","L6 IT","L6 IT Car3","L5 ET","L5/6 NP","L6 CT","L6b"),reference.cluster = c("L6 CT","L6b"))+ theme(legend.position = "none")+scale_fill_manual(values = color[c(1,2,4,7,8,3,5,6,9)])

my_comparisons <- list( c("L2/3 IT","L4/5 IT"),c("L4/5 IT","L5 IT"),c("L5 IT","L6 IT"))

tiff("/projects/b1042/YiLab/Cady/Code_3rdDraft/Merfish_3D//sample1_s50_Cortex.dist.3D.tiff", units="in", width=5, height=6, res=600)
scHolography::clusterDistanceBoxplot(scHolography.obj.slice3Dtoslice50,annotationToUse = "subclass",query.cluster.list = c(
  "L2/3 IT","L4/5 IT","L5 IT","L6 IT"),reference.cluster = c("L6 IT","L6 IT Car3","L6 CT","L6b"))+ theme(legend.position = "none")+scale_fill_manual(values = color[c(1,2,4,7,8,3,5,6,9)])+theme_classic()+ 
  theme(axis.title.x = element_blank(),axis.text.x = element_text(angle = 45,hjust=1),axis.title.y = element_text(size = 16,face = "bold"),axis.text = element_text(size = 15,face = "bold"))+NoLegend()+ylab("SMN Distance to L6")+ 
  geom_signif(comparisons = my_comparisons,map_signif_level = TRUE,test.args = list(size=5))

dev.off()
```


### scHolography Inference (slice1 Reference on slice1 Query)

```{r}
### Create an seurat object with spatial info
merfish.seurat.mouse1_sample1.slice1.sub@images$image =  new(
  Class = 'SlideSeq',
  assay = "Spatial",
  key = "image_",
  coordinates = merfish.seurat.mouse1_sample1.slice1.sub@meta.data[,c("CentroidX","CentroidY")]
)
```
```{r}

merfish.seurat.mouse1_sample1.slice1.sub_dup <- merfish.seurat.mouse1_sample1.slice1.sub
merfish.seurat.mouse1_sample1.slice1.sub_dup <- RenameCells(merfish.seurat.mouse1_sample1.slice1.sub_dup, paste0(colnames(merfish.seurat.mouse1_sample1.slice1.sub_dup),"_dup")) 

```


### scHolography Inference (slice1 Reference on Sample 1 Slices combined query)
```{r}
sp.integrated.merfish.slice3Dtoslice1 <- dataAlign(low.res.sp =  merfish.seurat.mouse1_sample1.slice1.sub_dup,high.res.sp =  merfish.seurat.mouse1_sample1.sub.comb,scProcessed = T,stProcessed = T,future.size = 7000)
scHolography.obj.slice3Dtoslice1 <- trainHolography(sp.integrated.merfish.slice3Dtoslice1)
saveRDS(scHolography.obj.slice3Dtoslice1,"/projects/b1042/YiLab/Cady/Code_3rdDraft/Merfish_3D/paste_sample1//merfish.slice3Dtoslice1.rds")


def.col <- rep("black",length(unique(scHolography.obj.slice3Dtoslice1$scHolography.sc$subclass)))
def.col[which(stringr::str_sort(unique(scHolography.obj.slice3Dtoslice1$scHolography.sc$subclass),numeric = T)%in%stringr::str_sort(unique(scHolography.obj.slice3Dtoslice1$scHolography.sc$subclass[which(scHolography.obj.slice3Dtoslice1$scHolography.sc$class_label%in%"Glutamatergic")]),numeric = T))] <-(RColorBrewer::brewer.pal(12,"Paired"))[1:9] 

fig.3dq <- scHolographyPlot(scHolography.obj.slice3Dtoslice1,color.by = "subclass",cells =which(scHolography.obj.slice3Dtoslice1$scHolography.sc$class_label%in%"Glutamatergic") ,color = def.col)%>% plotly::layout(scene = list(camera = list(eye = list(x = 1.5, z = .25, y = 0))))
fig.3dq

#plotly::orca(fig.3dq, "sample1_slice1.svg",width = 4.5,height = 6)
```

```{r}
fig.3dq.layer <-scHolographyPlot(scHolography.obj.slice3Dtoslice1,color.by = "Inferred_Z",cells =which(scHolography.obj.slice3Dtoslice1$scHolography.sc$class_label%in%"Glutamatergic"),color = c('#e41a1c','#377eb8','#4daf4a','#984ea3','#FF7F00','#FFFF33'))%>% plotly::layout(scene = list(camera = list(eye = list(x = 1.5, z = .25, y = 0))))
fig.3dq.layer
#plotly::orca(fig.3dq.layer, "fig.3dq.layer.svg",width = 4.5,height = 6)
```

```{r}

my_comparisons <- list( c("10","100"), c("100","210"), c("210","310"), c("310","400"),c('400','500'),c("10","210"), c("210","400"))
tiff("/projects/b1042/YiLab/Cady/Code_3rdDraft/Merfish_3D/sample1_s1_Cortex.dist.3D.layer.tiff", units="in", width=5, height=6, res=600)
scHolography::clusterDistanceBoxplot(scHolography.obj.slice3Dtoslice1,annotationToUse = "Inferred_Z",query.cluster.list = c("10", "100", "210", "310","400","500"),reference.cluster = c("10"))+ theme(legend.position = "none")+scale_fill_manual(values = c('#e41a1c','#377eb8','#4daf4a','#984ea3','#FF7F00','#FFFF33'))+theme_classic()+ 
  theme(axis.title.x = element_blank(),axis.text.x = element_text(angle = 45,hjust=1),axis.title.y = element_text(size = 16,face = "bold"),axis.text = element_text(size = 15,face = "bold"))+NoLegend()+ylab("SMN Distance to slice 10")+ 
  geom_signif(comparisons = my_comparisons,map_signif_level = TRUE,test.args = list(size=5),y_position = c(rep(4.5,5),rep(5,2)))
dev.off()
```


```{r}
scHolography::clusterDistanceBoxplot(scHolography.obj.slice3Dtoslice1,annotationToUse = "subclass",query.cluster.list = c(
  "L2/3 IT","L4/5 IT","L5 IT","L6 IT","L6 IT Car3","L5 ET","L5/6 NP","L6 CT"),reference.cluster = c("L6 CT","L6b"))+ theme(legend.position = "none")+scale_fill_manual(values = color[c(1,2,4,7,8,3,5,6)])

my_comparisons <- list( c("L2/3 IT","L4/5 IT"),c("L4/5 IT","L5 IT"),c("L5 IT","L6 IT"))

tiff("/projects/b1042/YiLab/Cady/Code_3rdDraft/Merfish_3D/sample1_s1_Cortex.dist.3D.tiff", units="in", width=5, height=6, res=600)
scHolography::clusterDistanceBoxplot(scHolography.obj.slice3Dtoslice1,annotationToUse = "subclass",query.cluster.list = c(
  "L2/3 IT","L4/5 IT","L5 IT","L6 IT"),reference.cluster = c("L6 IT","L6 IT Car3","L6 CT","L6b"))+ theme(legend.position = "none")+scale_fill_manual(values = color[c(1,2,4,7,8,3,5,6)])+theme_classic()+ 
  theme(axis.title.x = element_blank(),axis.text.x = element_text(angle = 45,hjust=1),axis.title.y = element_text(size = 16,face = "bold"),axis.text = element_text(size = 15,face = "bold"))+NoLegend()+ylab("SMN Distance to L6")+ 
  geom_signif(comparisons = my_comparisons,map_signif_level = TRUE,test.args = list(size=5))

dev.off()
```

```{r}
save.image("/projects/b1042/YiLab/Cady/Code_3rdDraft/Merfish_3D/paste_sample1//merfish.seurat.mouse1_sample1.RData")
```